import { describe, expect, it } from 'vitest';
import { applyPlanUpdate, approvePlan, createBlankPlan, evaluatePlan, repairPlan, reservePlan, snapshotPlan, solvePlan } from '../src/domain';
import { defaultPreferences } from '../src/data';
import { searchShowtimeInventory } from '../src/providers';

const input=(overrides:Partial<Parameters<typeof solvePlan>[0]>={})=>({city:'Dhaka' as const,date:'2026-09-04',people:3,budget:5000,preferences:defaultPreferences(),dinnerDurationMinutes:75,bufferMinutes:15,...overrides});
const validPlan=()=>{const result=solvePlan(input());if(!result.ok)throw new Error(result.error.message);return result.plan;};

describe('feasibility solver',()=>{
  it('produces a complete chronological plan with explicit evidence',()=>{const result=solvePlan(input());expect(result.ok).toBe(true);if(!result.ok)return;expect(result.evaluation.valid).toBe(true);expect(result.evaluation.timeline!.slackMinutes).toBeGreaterThanOrEqual(0);expect(result.evaluation.checks.every(check=>check.passed)).toBe(true);expect(result.evaluation.costs.total).toBeLessThanOrEqual(5000);expect(result.considered).toBeGreaterThan(20);});
  it('returns no feasible plan for an insufficient budget',()=>{const result=solvePlan(input({budget:500}));expect(result.ok).toBe(false);if(result.ok)return;expect(result.error.code).toBe('NO_FEASIBLE_PLAN');});
  it('returns no availability for an unsupported date',()=>{const result=solvePlan(input({date:'2026-12-31'}));expect(result.ok).toBe(false);if(result.ok)return;expect(result.error.code).toBe('NO_RESTAURANT_AVAILABILITY');});
  it('returns no showtimes for an unsupported inventory date',()=>{expect(searchShowtimeInventory({city:'Dhaka',date:'2026-12-31',people:3})).toEqual([]);});
  it('uses cuisine preference in ranking',()=>{const result=solvePlan(input({budget:6500,preferences:{...defaultPreferences(),cuisine:'Italian'}}));expect(result.ok).toBe(true);if(result.ok)expect(result.plan.selections.restaurantId).toBe('pasta-fresco');});
  it('uses movie genre preference in ranking',()=>{const result=solvePlan(input({preferences:{...defaultPreferences(),movieGenre:'Comedy'}}));expect(result.ok).toBe(true);if(result.ok)expect(result.plan.selections.movieId).toBe('laugh-track');});
  it('uses comfort preference in transport ranking',()=>{const result=solvePlan(input({budget:6500,preferences:{...defaultPreferences(),transport:'comfortable'}}));expect(result.ok).toBe(true);if(result.ok)expect(result.plan.selections.transportOptionId).toContain('comfort');});
});

describe('plan integrity and chronology',()=>{
  it('detects an impossible dinner-to-movie sequence',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:30',movieId:'paper-moons',showtimeId:'pm-2026-09-04-2000',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.valid).toBe(false);expect(evaluation.checks.find(check=>check.id==='chronology')?.passed).toBe(false);});
  it('accepts the exact chronology boundary',()=>{const plan=createBlankPlan();plan.bufferMinutes=23;plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:00',movieId:'the-last-signal',showtimeId:'tls-2026-09-04-2015',transportOptionId:'dhanmondi-27--bashundhara-city--metro'};const evaluation=evaluatePlan(plan);expect(evaluation.timeline?.slackMinutes).toBe(0);expect(evaluation.checks.find(check=>check.id==='chronology')?.passed).toBe(true);});
  it('rejects movie and showtime mismatch without pricing it as zero',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:00',movieId:'paper-moons',showtimeId:'tls-2026-09-04-2015',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.valid).toBe(false);expect(evaluation.costs.movie).toBeNull();expect(evaluation.checks.find(check=>check.id==='showtime_integrity')?.passed).toBe(false);});
  it('rejects showtime on the wrong date',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:00',movieId:'the-last-signal',showtimeId:'tls-2026-09-05-2015',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};expect(evaluatePlan(plan).checks.find(check=>check.id==='showtime_integrity')?.passed).toBe(false);});
  it('derives the cinema from the showtime instead of accepting a mismatched cinema field',()=>{const plan=createBlankPlan();plan.selections={movieId:'the-last-signal',showtimeId:'tls-2026-09-04-2015'};expect(snapshotPlan(plan).cinema?.id).toBe('star-bashundhara');});
});

describe('versioned updates, approval, and reservation',()=>{
  it('rejects stale versions',()=>{const plan=validPlan();const result=applyPlanUpdate(plan,{expectedVersion:plan.version-1,budget:6000});expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('STALE_PLAN_VERSION');});
  it('rejects movie/showtime mismatch atomically',()=>{const plan=validPlan();const result=applyPlanUpdate(plan,{expectedVersion:plan.version,movieId:'paper-moons',showtimeId:'tls-2026-09-04-2015'});expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('MOVIE_SHOWTIME_MISMATCH');});
  it('clears a transport option when venue route changes',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:00',movieId:'paper-moons',showtimeId:'pm-2026-09-04-2000',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};const result=applyPlanUpdate(plan,{expectedVersion:plan.version,movieId:'the-last-signal',showtimeId:'tls-2026-09-04-2015'});expect(result.ok).toBe(true);if(result.ok){expect(result.data.clearedDependencies).toContain('transportOptionId');expect(result.data.plan.selections.transportOptionId).toBeUndefined();}});
  it('increments version and invalidates prior approval on edits',()=>{const plan=validPlan();const approved=approvePlan(plan,plan.version);expect(approved.ok).toBe(true);if(!approved.ok)return;const changed=applyPlanUpdate(approved.data.plan,{expectedVersion:plan.version,budget:5500});expect(changed.ok).toBe(true);if(changed.ok){expect(changed.data.plan.version).toBe(plan.version+1);expect(changed.data.plan.approval).toBeUndefined();}});
  it('blocks empty plan approval',()=>{const plan=createBlankPlan();const result=approvePlan(plan,plan.version);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('PLAN_INVALID');});
  it('blocks incomplete plan approval',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:00'};const result=approvePlan(plan,plan.version);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.details).toContain('Restaurant slot, movie showtime, and route transport are all required.');});
  it('blocks approval with a stale version',()=>{const plan=validPlan();const result=approvePlan(plan,plan.version-1);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('STALE_PLAN_VERSION');});
  it('blocks over-budget approval',()=>{const plan=validPlan();plan.budget=500;const result=approvePlan(plan,plan.version);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.details?.join(' ')).toMatch(/Budget exceeded/);});
  it('approves only a valid current version',()=>{const plan=validPlan();const result=approvePlan(plan,plan.version);expect(result.ok).toBe(true);if(result.ok){expect(result.data.plan.status).toBe('approved');expect(result.data.plan.approval?.version).toBe(plan.version);}});
  it('requires exact approval before reservation and rejects repeats',()=>{const plan=validPlan();const early=reservePlan(plan,plan.version);expect(early.ok).toBe(false);const approved=approvePlan(plan,plan.version);if(!approved.ok)throw new Error('approval failed');const reserved=reservePlan(approved.data.plan,plan.version);expect(reserved.ok).toBe(true);if(!reserved.ok)return;expect(reserved.data.reservationId).toMatch(/^SIM-/);const repeated=reservePlan(reserved.data.plan,plan.version);expect(repeated.ok).toBe(false);if(!repeated.ok)expect(repeated.error.code).toBe('RESERVATION_ALREADY_EXISTS');});
  it('repairs an invalid human budget edit while preserving dinner',()=>{const plan=validPlan();const changed=applyPlanUpdate(plan,{expectedVersion:plan.version,restaurantId:'saffron-table',restaurantSlot:'18:15'});if(!changed.ok)throw new Error('edit failed');const repaired=repairPlan(changed.data.plan,{expectedVersion:changed.data.plan.version,preserveRestaurant:true,preserveMovie:false});expect(repaired.ok).toBe(true);if(repaired.ok){expect(repaired.plan.selections.restaurantId).toBe('saffron-table');expect(repaired.evaluation.valid).toBe(true);}});
  it('keeps a valid route while an agent changes the movie and recomputes the total',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'17:45',movieId:'paper-moons',showtimeId:'pm-2026-09-04-2000',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};const before=evaluatePlan(plan);expect(before.valid).toBe(true);const changed=applyPlanUpdate(plan,{expectedVersion:plan.version,movieId:'monsoon-code',showtimeId:'mc-2026-09-04-2045'});expect(changed.ok).toBe(true);if(!changed.ok)return;expect(changed.data.plan.selections.transportOptionId).toBe('dhanmondi-27--jamuna-future-park--economy');expect(changed.data.evaluation.valid).toBe(true);expect(changed.data.evaluation.costs.total).not.toBe(before.costs.total);});
});
