import { beforeEach, describe, expect, it } from 'vitest';
import { applyPlanUpdate, approvePlan, createBlankPlan, evaluatePlan, repairPlan, reservePlan, snapshotPlan, solvePlan } from '../src/domain';
import { defaultPreferences } from '../src/data';
import { demoProvider, MutableDemoProvider, searchShowtimeInventory } from '../src/providers';

const input=(overrides:Partial<Parameters<typeof solvePlan>[0]>={})=>({city:'Dhaka' as const,date:'2026-09-04',people:3,budget:5000,preferences:defaultPreferences(),dinnerDurationMinutes:75,bufferMinutes:15,...overrides});
const validPlan=()=>{const result=solvePlan(input());if(!result.ok)throw new Error(result.error.message);return result.plan;};
beforeEach(()=>demoProvider.reset());

describe('feasibility solver',()=>{
  it('produces a complete chronological plan with explicit evidence',()=>{const result=solvePlan(input());expect(result.ok).toBe(true);if(!result.ok)return;expect(result.evaluation.valid).toBe(true);expect(result.evaluation.timeline!.slackMinutes).toBeGreaterThanOrEqual(0);expect(result.evaluation.checks.every(check=>check.passed)).toBe(true);expect(result.evaluation.costs.total).toBeLessThanOrEqual(5000);expect(result.considered).toBeGreaterThan(20);});
  it('returns no feasible plan for an insufficient budget',()=>{const result=solvePlan(input({budget:500}));expect(result.ok).toBe(false);if(result.ok)return;expect(result.error.code).toBe('NO_FEASIBLE_PLAN');});
  it('generates dated inventory through the supported window boundary',()=>{const result=solvePlan(input({date:'2026-09-16'}));expect(result.ok).toBe(true);});
  it('returns no invented inventory outside the supported window',()=>{expect(searchShowtimeInventory({city:'Dhaka',date:'2026-09-17',people:3})).toEqual([]);expect(searchShowtimeInventory({city:'Dhaka',date:'2026-09-02',people:3})).toEqual([]);});
  it('uses cuisine preference in ranking',()=>{const result=solvePlan(input({budget:6500,preferences:{...defaultPreferences(),cuisine:'Italian'}}));expect(result.ok).toBe(true);if(result.ok)expect(result.plan.selections.restaurantId).toBe('pasta-fresco');});
  it('uses movie genre preference in ranking',()=>{const result=solvePlan(input({preferences:{...defaultPreferences(),movieGenre:'Comedy'}}));expect(result.ok).toBe(true);if(result.ok)expect(result.plan.selections.movieId).toBe('laugh-track');});
  it('uses comfort preference in transport ranking',()=>{const result=solvePlan(input({budget:6500,preferences:{...defaultPreferences(),transport:'comfortable'}}));expect(result.ok).toBe(true);if(result.ok)expect(result.plan.selections.transportOptionId).toContain('comfort');});
});

describe('plan integrity and chronology',()=>{
  it('detects a table booked before you could arrive from the cinema',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'19:30',movieId:'the-last-signal',showtimeId:'tls-2026-09-04-1645',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.valid).toBe(false);expect(evaluation.timeline?.slackMinutes).toBe(-7);expect(evaluation.checks.find(check=>check.id==='chronology')?.passed).toBe(false);});
  it('accepts the exact chronology boundary',()=>{const plan=createBlankPlan();plan.bufferMinutes=8;plan.selections={restaurantId:'bistro-17',restaurantSlot:'19:30',movieId:'the-last-signal',showtimeId:'tls-2026-09-04-1645',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.timeline?.slackMinutes).toBe(0);expect(evaluation.checks.find(check=>check.id==='chronology')?.passed).toBe(true);});
  it('orders the timeline movie, travel, then dinner',()=>{const plan=createBlankPlan();plan.bufferMinutes=15;plan.selections={restaurantId:'bistro-17',restaurantSlot:'20:00',movieId:'the-last-signal',showtimeId:'tls-2026-09-04-1645',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};const timeline=evaluatePlan(plan).timeline!;expect(timeline.movieStart).toBe('16:45');expect(timeline.movieEnd).toBe('18:53');expect(timeline.departAt).toBe('18:53');expect(timeline.arriveAt).toBe('19:22');expect(timeline.readyAt).toBe('19:37');expect(timeline.dinnerStart).toBe('20:00');expect(timeline.dinnerEnd).toBe('21:15');});
  it('rejects a 99-minute idle gap between the film and the table',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'21:30',movieId:'paper-moons',showtimeId:'pm-2026-09-04-1700',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.timeline?.slackMinutes).toBe(99);expect(evaluation.checks.find(check=>check.id==='chronology')).toMatchObject({passed:false});});
  it('enforces relaxed timing at 90 minutes and rejects 91',()=>{const plan=createBlankPlan();plan.bufferMinutes=24;plan.selections={restaurantId:'bistro-17',restaurantSlot:'21:30',movieId:'paper-moons',showtimeId:'pm-2026-09-04-1700',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};expect(evaluatePlan(plan).timeline?.slackMinutes).toBe(90);expect(evaluatePlan(plan).checks.find(item=>item.id==='chronology')?.passed).toBe(true);plan.bufferMinutes=23;expect(evaluatePlan(plan).timeline?.slackMinutes).toBe(91);expect(evaluatePlan(plan).checks.find(item=>item.id==='chronology')?.passed).toBe(false);});
  it('enforces compact timing at 45 minutes and rejects 46',()=>{const plan=createBlankPlan();plan.preferences.timing='compact';plan.bufferMinutes=9;plan.selections={restaurantId:'bistro-17',restaurantSlot:'20:30',movieId:'paper-moons',showtimeId:'pm-2026-09-04-1700',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};expect(evaluatePlan(plan).timeline?.slackMinutes).toBe(45);expect(evaluatePlan(plan).checks.find(item=>item.id==='chronology')?.passed).toBe(true);plan.bufferMinutes=8;expect(evaluatePlan(plan).timeline?.slackMinutes).toBe(46);expect(evaluatePlan(plan).checks.find(item=>item.id==='chronology')?.passed).toBe(false);});
  it('rejects a dinner that runs past the restaurant closing time',()=>{const plan=createBlankPlan();plan.dinnerDurationMinutes=120;plan.bufferMinutes=15;plan.selections={restaurantId:'riverstone',restaurantSlot:'21:00',movieId:'monsoon-code',showtimeId:'mc-2026-09-04-1745',transportOptionId:'uttara-7--jamuna-future-park--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.checks.find(check=>check.id==='restaurant_hours')?.passed).toBe(false);expect(evaluation.valid).toBe(false);});
  it('accepts a dinner that finishes inside the opening window',()=>{const plan=createBlankPlan();plan.dinnerDurationMinutes=75;plan.bufferMinutes=15;plan.selections={restaurantId:'riverstone',restaurantSlot:'21:00',movieId:'monsoon-code',showtimeId:'mc-2026-09-04-1745',transportOptionId:'uttara-7--jamuna-future-park--economy'};expect(evaluatePlan(plan).checks.find(check=>check.id==='restaurant_hours')?.passed).toBe(true);});
  it('rejects movie and showtime mismatch without pricing it as zero',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'20:00',movieId:'paper-moons',showtimeId:'tls-2026-09-04-1645',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};const evaluation=evaluatePlan(plan);expect(evaluation.valid).toBe(false);expect(evaluation.costs.movie).toBeNull();expect(evaluation.checks.find(check=>check.id==='showtime_integrity')?.passed).toBe(false);});
  it('rejects showtime on the wrong date',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'20:00',movieId:'the-last-signal',showtimeId:'tls-2026-09-05-1645',transportOptionId:'dhanmondi-27--bashundhara-city--economy'};expect(evaluatePlan(plan).checks.find(check=>check.id==='showtime_integrity')?.passed).toBe(false);});
  it('derives the cinema from the showtime instead of accepting a mismatched cinema field',()=>{const plan=createBlankPlan();plan.selections={movieId:'the-last-signal',showtimeId:'tls-2026-09-04-1645'};expect(snapshotPlan(plan).cinema?.id).toBe('star-bashundhara');});
});

describe('versioned updates, approval, and reservation',()=>{
  it('rejects stale versions',()=>{const plan=validPlan();const result=applyPlanUpdate(plan,{expectedVersion:plan.version+1,budget:6000});expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('STALE_PLAN_VERSION');});
  it('does not increment the version for unchanged input',()=>{const plan=validPlan();const result=applyPlanUpdate(plan,{expectedVersion:plan.version,budget:plan.budget});expect(result.ok).toBe(true);if(result.ok){expect(result.data.changed).toBe(false);expect(result.data.plan).toBe(plan);expect(result.data.plan.version).toBe(plan.version);}});
  it('rejects movie/showtime mismatch atomically',()=>{const plan=validPlan();const result=applyPlanUpdate(plan,{expectedVersion:plan.version,movieId:'paper-moons',showtimeId:'tls-2026-09-04-1645'});expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('MOVIE_SHOWTIME_MISMATCH');});
  it('clears a transport option when venue route changes',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'20:00',movieId:'paper-moons',showtimeId:'pm-2026-09-04-1700',transportOptionId:'dhanmondi-27--jamuna-future-park--economy'};const result=applyPlanUpdate(plan,{expectedVersion:plan.version,movieId:'the-last-signal',showtimeId:'tls-2026-09-04-1645'});expect(result.ok).toBe(true);if(result.ok){expect(result.data.clearedDependencies).toContain('transportOptionId');expect(result.data.plan.selections.transportOptionId).toBeUndefined();}});
  it('increments version and invalidates prior approval on edits',()=>{const plan=validPlan();const approved=approvePlan(plan,plan.version);expect(approved.ok).toBe(true);if(!approved.ok)return;const changed=applyPlanUpdate(approved.data.plan,{expectedVersion:plan.version,budget:5500});expect(changed.ok).toBe(true);if(changed.ok){expect(changed.data.plan.version).toBe(plan.version+1);expect(changed.data.plan.approval).toBeUndefined();}});
  it('blocks empty plan approval',()=>{const plan=createBlankPlan();const result=approvePlan(plan,plan.version);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('PLAN_INVALID');});
  it('blocks incomplete plan approval',()=>{const plan=createBlankPlan();plan.selections={restaurantId:'bistro-17',restaurantSlot:'18:00'};const result=approvePlan(plan,plan.version);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.details).toContain('Restaurant slot, movie showtime, and route transport are all required.');});
  it('blocks approval with a stale version',()=>{const plan=validPlan();const result=approvePlan(plan,plan.version-1);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.code).toBe('STALE_PLAN_VERSION');});
  it('blocks over-budget approval',()=>{const plan=validPlan();plan.budget=500;const result=approvePlan(plan,plan.version);expect(result.ok).toBe(false);if(!result.ok)expect(result.error.details?.join(' ')).toMatch(/Budget exceeded/);});
  it('approves only a valid current version',()=>{const plan=validPlan();const result=approvePlan(plan,plan.version);expect(result.ok).toBe(true);if(result.ok){expect(result.data.plan.status).toBe('approved');expect(result.data.plan.approval?.version).toBe(plan.version);}});
  it('requires exact approval and returns repeat confirmations idempotently',async()=>{const plan=validPlan();const early=await reservePlan(plan,plan.version);expect(early.ok).toBe(false);const approved=approvePlan(plan,plan.version);if(!approved.ok)throw new Error('approval failed');const reserved=await reservePlan(approved.data.plan,plan.version);expect(reserved.ok).toBe(true);if(!reserved.ok)return;expect(reserved.data.reservationId).toMatch(/^SBX-/);const repeated=await reservePlan(reserved.data.plan,plan.version);expect(repeated.ok).toBe(true);if(repeated.ok){expect(repeated.data.idempotent).toBe(true);expect(repeated.data.reservationId).toBe(reserved.data.reservationId);}});
  it('decrements both inventories exactly once on sandbox confirmation',async()=>{const provider=new MutableDemoProvider();const result=solvePlan(input(),0,undefined,provider);if(!result.ok)throw new Error('solve failed');const before=snapshotPlan(result.plan,provider);const approved=approvePlan(result.plan,result.plan.version,provider);if(!approved.ok)throw new Error('approval failed');const reserved=await reservePlan(approved.data.plan,result.plan.version,provider);expect(reserved.ok).toBe(true);const after=snapshotPlan(reserved.ok?reserved.data.plan:approved.data.plan,provider);expect(after.showtime!.seatsRemaining).toBe(before.showtime!.seatsRemaining-3);expect(provider.availableRestaurantSlots(after.restaurant!,result.plan.date,1).find(item=>item.time===result.plan.selections.restaurantSlot)?.capacityRemaining).toBe(before.restaurant!.slots.find(item=>item.date==='2026-09-04'&&item.time===result.plan.selections.restaurantSlot)!.capacityRemaining-3);const revision=provider.revision;await reservePlan(reserved.ok?reserved.data.plan:approved.data.plan,result.plan.version,provider);expect(provider.revision).toBe(revision);});
  it('keeps an exact-capacity reservation valid for its owner and exposes authoritative snapshots',async()=>{const provider=new MutableDemoProvider();const solved=solvePlan(input(),0,undefined,provider);if(!solved.ok)throw new Error('solve failed');provider.setRestaurantCapacity(solved.plan.selections.restaurantId!,solved.plan.date,solved.plan.selections.restaurantSlot!,solved.plan.people);const approved=approvePlan(solved.plan,solved.plan.version,provider);if(!approved.ok)throw new Error('approval failed');const reserved=await reservePlan(approved.data.plan,approved.data.plan.version,provider);if(!reserved.ok)throw new Error('reservation failed');const snapshot=snapshotPlan(reserved.data.plan,provider);expect(snapshot.evaluation.valid).toBe(true);expect(snapshot.restaurant?.slots.find(item=>item.time===reserved.data.plan.selections.restaurantSlot)).toMatchObject({capacityRemaining:0,inventoryState:'committed_to_current_plan',committedQuantity:3});expect(snapshot.showtime).toMatchObject({inventoryState:'committed_to_current_plan',committedQuantity:3});const other={...reserved.data.plan,id:'other-plan',status:'valid' as const,reservation:undefined};expect(evaluatePlan(other,provider).checks.find(item=>item.id==='restaurant_availability')?.passed).toBe(false);});
  it('rejects stale approval after provider inventory changes',async()=>{const provider=new MutableDemoProvider();const result=solvePlan(input(),0,undefined,provider);if(!result.ok)throw new Error('solve failed');const approved=approvePlan(result.plan,result.plan.version,provider);if(!approved.ok)throw new Error('approval failed');provider.setShowtimeSeats(result.plan.selections.showtimeId!,0);const reserved=await reservePlan(approved.data.plan,result.plan.version,provider);expect(reserved.ok).toBe(false);if(!reserved.ok)expect(reserved.error.code).toBe('PROVIDER_STATE_CHANGED');});
  it('surfaces provider conflict and failure without consuming inventory',()=>{const provider=new MutableDemoProvider();const plan=validPlan();provider.setRestaurantCapacity(plan.selections.restaurantId!,plan.date,plan.selections.restaurantSlot!,0);expect(provider.reserve(plan)).toMatchObject({ok:false,error:{code:'PROVIDER_CONFLICT'}});provider.reset();provider.simulateNextReservationFailure();expect(provider.reserve(plan)).toMatchObject({ok:false,error:{code:'PROVIDER_UNAVAILABLE'}});expect(provider.revision).toBe(0);});
  it('records a failed reservation state and releases attempted inventory',async()=>{const provider=new MutableDemoProvider();const solved=solvePlan(input(),0,undefined,provider);if(!solved.ok)throw new Error('solve failed');const approved=approvePlan(solved.plan,solved.plan.version,provider);if(!approved.ok)throw new Error('approval failed');provider.simulateNextReservationFailure();const failed=await reservePlan(approved.data.plan,approved.data.plan.version,provider);expect(failed.ok).toBe(false);if(failed.ok)return;expect(failed.transitions).toEqual(['approved','reservation_pending','reservation_failed']);expect(failed.plan).toMatchObject({status:'reservation_failed',approval:undefined,reservation:{status:'failed',failureCode:'PROVIDER_UNAVAILABLE'}});expect(failed.plan?.reservation?.inventory.every(item=>item.state==='released')).toBe(true);expect(provider.revision).toBe(0);});
  it('repairs an invalid human budget edit while preserving dinner',()=>{const plan=validPlan();const changed=applyPlanUpdate(plan,{expectedVersion:plan.version,restaurantId:'saffron-table',restaurantSlot:'20:15'});if(!changed.ok)throw new Error('edit failed');const repaired=repairPlan(changed.data.plan,{expectedVersion:changed.data.plan.version,preserveRestaurant:true,preserveMovie:false});expect(repaired.ok).toBe(true);if(repaired.ok){expect(repaired.plan.selections.restaurantId).toBe('saffron-table');expect(repaired.evaluation.valid).toBe(true);}});
  it('keeps a valid route while an agent changes the movie and recomputes the total',()=>{const plan=createBlankPlan();plan.budget=6500;plan.selections={restaurantId:'smoke-house',restaurantSlot:'20:30',movieId:'paper-moons',showtimeId:'pm-2026-09-04-1700',transportOptionId:'banani-11--jamuna-future-park--economy'};const before=evaluatePlan(plan);expect(before.valid).toBe(true);const changed=applyPlanUpdate(plan,{expectedVersion:plan.version,movieId:'monsoon-code',showtimeId:'mc-2026-09-04-1745'});expect(changed.ok).toBe(true);if(!changed.ok)return;expect(changed.data.plan.selections.transportOptionId).toBe('banani-11--jamuna-future-park--economy');expect(changed.data.evaluation.valid).toBe(true);expect(changed.data.evaluation.costs.total).not.toBe(before.costs.total);});
});
