import { beforeEach, describe, expect, it } from 'vitest';
import { initialPlan, defaultPreferences } from '../src/data';
import { approvePlan } from '../src/domain';
import { buildTools, resultErrorCode, toolNames } from '../src/tools';
import { Plan } from '../src/types';
import { demoProvider } from '../src/providers';

function harness(){let plan:Plan=initialPlan();const changes:string[]=[];const tools=buildTools(()=>plan,(next,activity)=>{plan=next;changes.push(activity)});return{tools,get plan(){return plan},set plan(value:Plan){plan=value},changes,call:(name:string,input:unknown)=>tools.find(tool=>tool.name===name)!.execute(input)};}
beforeEach(()=>demoProvider.reset());
describe('WebMCP handlers',()=>{
  it('exposes only meaningful tools with strict schemas',()=>{const h=harness();expect(h.tools.map(tool=>tool.name)).toEqual(toolNames);for(const tool of h.tools){expect(tool.description.length).toBeGreaterThan(70);expect(tool.inputSchema.additionalProperties).toBe(false);}});
  it('advertises the same critical bounds enforced at runtime',()=>{const h=harness();const create=h.tools.find(tool=>tool.name==='create_evening_plan')!.inputSchema as {properties:Record<string,{minimum?:number;maximum?:number;enum?:string[]}>};const update=h.tools.find(tool=>tool.name==='update_plan')!.inputSchema as {properties:Record<string,{minimum?:number;maximum?:number}>};expect(create.properties.date.enum).toEqual(expect.arrayContaining(['2026-09-03','2026-09-16']));expect(create.properties.people).toMatchObject({minimum:1,maximum:12});expect(create.properties.budget).toMatchObject({minimum:500,maximum:100000});expect(update.properties.expectedVersion.minimum).toBe(1);expect(update.properties.budget.maximum).toBe(100000);});
  it('rejects malformed calls inside handlers',async()=>{const h=harness();expect(resultErrorCode(await h.call('create_evening_plan',{city:'Dhaka',date:'2026-09-04',people:50,budget:5000,preferences:defaultPreferences()}))).toBe('INVALID_INPUT');expect(resultErrorCode(await h.call('search_restaurants',null))).toBe('INVALID_INPUT');expect(resultErrorCode(await h.call('search_restaurants','{"city":"Dhaka"}'))).toBe('INVALID_INPUT');expect(resultErrorCode(await h.call('get_current_plan',{extra:true}))).toBe('INVALID_INPUT');});
  it('rejects malformed input in every handler',async()=>{const h=harness();for(const name of toolNames)expect(resultErrorCode(await h.call(name,{unexpected:true})),name).toBe('INVALID_INPUT');});
  it('includes current plan and provider context in every error',async()=>{const h=harness();for(const name of toolNames){const result=await h.call(name,{unexpected:true}) as {ok:false;error:{context?:unknown}};expect(result.error.context,name).toEqual({planVersion:1,providerRevision:0});}});
  it('returns route-specific estimates and rejects unknown or unsupported routes',async()=>{const h=harness();const dhaka=await h.call('estimate_transport',{fromLocationId:'dhanmondi-27',toLocationId:'bashundhara-city'});expect(dhaka).toMatchObject({ok:true,data:{distanceKm:6.2,options:expect.arrayContaining([expect.objectContaining({durationMinutes:expect.any(Number),fare:expect.any(Number)})])}});expect(resultErrorCode(await h.call('estimate_transport',{fromLocationId:'mars',toLocationId:'moon'}))).toBe('UNKNOWN_LOCATION');expect(resultErrorCode(await h.call('estimate_transport',{fromLocationId:'bashundhara-city',toLocationId:'dhanmondi-27'}))).toBe('ROUTE_NOT_FOUND');});
  it('creates a valid version and updates shared state',async()=>{const h=harness();const result=await h.call('create_evening_plan',{city:'Dhaka',date:'2026-09-04',people:3,budget:5000,preferences:defaultPreferences(),dinnerDurationMinutes:75,bufferMinutes:15});expect(result).toMatchObject({ok:true,data:{plan:{evaluation:{valid:true}}}});expect(h.plan.version).toBe(2);expect(h.changes).toHaveLength(1);});
  it('treats an identical update as a no-op without a write or version increment',async()=>{const h=harness();const result=await h.call('update_plan',{expectedVersion:1,budget:5000});expect(result).toMatchObject({ok:true,data:{changed:false,context:{planVersion:1,providerRevision:0}}});expect(h.plan.version).toBe(1);expect(h.changes).toHaveLength(0);});
  it('rejects unknown showtimes and empty updates',async()=>{const h=harness();await h.call('create_evening_plan',{city:'Dhaka',date:'2026-09-04',people:3,budget:5000,preferences:defaultPreferences()});expect(resultErrorCode(await h.call('update_plan',{expectedVersion:h.plan.version,movieId:'paper-moons',showtimeId:'missing'}))).toBe('UNKNOWN_SHOWTIME');expect(resultErrorCode(await h.call('update_plan',{expectedVersion:h.plan.version}))).toBe('INVALID_INPUT');});
  it('blocks stale and unapproved reservations, then confirms idempotently',async()=>{const h=harness();await h.call('create_evening_plan',{city:'Dhaka',date:'2026-09-04',people:3,budget:5000,preferences:defaultPreferences()});expect(resultErrorCode(await h.call('reserve_plan',{expectedVersion:h.plan.version-1,confirmation:'CONFIRM_SIMULATED_RESERVATION'}))).toBe('STALE_PLAN_VERSION');expect(resultErrorCode(await h.call('reserve_plan',{expectedVersion:h.plan.version,confirmation:'CONFIRM_SIMULATED_RESERVATION'}))).toBe('HUMAN_APPROVAL_REQUIRED');const approved=approvePlan(h.plan,h.plan.version);if(!approved.ok)throw new Error('approval failed');h.plan=approved.data.plan;const reserved=await h.call('reserve_plan',{expectedVersion:h.plan.version,confirmation:'CONFIRM_SIMULATED_RESERVATION'});expect(reserved).toMatchObject({ok:true,data:{idempotent:false}});expect(await h.call('reserve_plan',{expectedVersion:h.plan.version,confirmation:'CONFIRM_SIMULATED_RESERVATION'})).toMatchObject({ok:true,data:{idempotent:true}});});
  it('returns post-reservation provider state that stays valid for the owning plan',async()=>{const h=harness();await h.call('create_evening_plan',{city:'Dhaka',date:'2026-09-04',people:3,budget:5000,preferences:defaultPreferences()});const approved=approvePlan(h.plan,h.plan.version);if(!approved.ok)throw new Error('approval failed');h.plan=approved.data.plan;await h.call('reserve_plan',{expectedVersion:h.plan.version,confirmation:'CONFIRM_SIMULATED_RESERVATION'});const current=await h.call('get_current_plan',{}) as {ok:true;data:{evaluation:{valid:boolean};restaurant:{slots:Array<{inventoryState:string}>};showtime:{inventoryState:string};context:unknown}};expect(current.data.evaluation.valid).toBe(true);expect(current.data.restaurant.slots.some(item=>item.inventoryState==='committed_to_current_plan')).toBe(true);expect(current.data.showtime.inventoryState).toBe('committed_to_current_plan');expect(current.data.context).toBeDefined();});
  it('has a successful execution path for every tool',async()=>{const h=harness();const base={city:'Dhaka',date:'2026-09-04',people:3};expect(await h.call('search_restaurants',base)).toMatchObject({ok:true});expect(await h.call('get_restaurant_details',{restaurantId:'bistro-17'})).toMatchObject({ok:true});expect(await h.call('check_restaurant_availability',{restaurantId:'bistro-17',date:base.date,people:3})).toMatchObject({ok:true});expect(await h.call('find_showtimes',base)).toMatchObject({ok:true});expect(await h.call('estimate_transport',{fromLocationId:'dhanmondi-27',toLocationId:'bashundhara-city'})).toMatchObject({ok:true});expect(await h.call('create_evening_plan',{...base,budget:5000,preferences:defaultPreferences()})).toMatchObject({ok:true});expect(await h.call('get_current_plan',{})).toMatchObject({ok:true});expect(await h.call('validate_plan',{})).toMatchObject({ok:true});expect(await h.call('calculate_total_cost',{})).toMatchObject({ok:true});expect(await h.call('update_plan',{expectedVersion:h.plan.version,budget:5100})).toMatchObject({ok:true});expect(await h.call('repair_plan',{expectedVersion:h.plan.version,preserveRestaurant:true,preserveMovie:false})).toMatchObject({ok:true});const approved=approvePlan(h.plan,h.plan.version);if(!approved.ok)throw new Error('approval failed');h.plan=approved.data.plan;expect(await h.call('reserve_plan',{expectedVersion:h.plan.version,confirmation:'CONFIRM_SIMULATED_RESERVATION'})).toMatchObject({ok:true});expect(h.changes.length).toBeGreaterThanOrEqual(4);});
});
