import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, ArrowRight, Bot, CalendarDays, Check, CheckCircle2, CircleDollarSign, Clock3, Copy, History, MapPin, Navigation, Pencil, RefreshCw, Route as RouteIcon, ShieldCheck, Sparkles, Star, Ticket, Utensils, Wrench, XCircle } from 'lucide-react';
import { cinemas, movies, restaurants } from './data';
import { applyPlanUpdate, approvePlan, createBlankPlan, evaluatePlan, repairPlan, reservePlan, snapshotPlan, solvePlan } from './domain';
import { compareAndSwapState, loadState, subscribeState } from './persistence';
import { demoProvider } from './providers';
import { buildTools, toolNames } from './tools';
import { Activity, ActivitySource, Plan, Preferences, Tab, ToolError } from './types';
import { constraintsSchema, parseInput } from './validation';

const money=(value:number|null|undefined)=>value==null?'—':`৳${value.toLocaleString('en-IN')}`;
const prettyTime=(value?:string)=>value?new Date(`2026-01-01T${value}:00`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—';
const uid=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const sourceLabel:Record<ActivitySource,string>={'human':'Human edit','external-agent':'WebMCP tool execution','quick-planner':'Local deterministic solver','system':'Workspace sync'};
const statusLabel=(plan:Plan,evaluation:ReturnType<typeof evaluatePlan>)=>plan.status==='reserved'?'Reservation confirmed':plan.status==='reservation_pending'?'Confirmation in progress':plan.status==='reservation_failed'?'Reservation needs retry':evaluation.valid?'Ready to review':plan.selections.restaurantId?'Plan needs attention':'Start your plan';
type WebMcpState='registering'|'active'|'unavailable'|'error';
type MutationOutcome={ok:true}|{ok:false;error:ToolError};

export default function App(){
  const [restored]=useState(()=>{const state=loadState();demoProvider.reset();demoProvider.importState(state.provider);return state;});
  const [tab,setTab]=useState<Tab>(()=>restored.plan.selections.restaurantId?'plan':'goal');
  const [plan,setPlanState]=useState<Plan>(restored.plan);
  const [activity,setActivity]=useState<Activity[]>(restored.activity);
  const [providerTick,setProviderTick]=useState(demoProvider.revision);
  const [syncMessage,setSyncMessage]=useState('This browser tab is current.');
  const [webmcp,setWebmcp]=useState<WebMcpState>(()=>typeof document.modelContext?.registerTool==='function'?'registering':'unavailable');
  const [toast,setToast]=useState<{tone:'ok'|'error';text:string}|null>(null);
  const planRef=useRef(plan);const activityRef=useRef(activity);const writerId=useRef(uid());
  const snapshot=useMemo(()=>{void providerTick;return snapshotPlan(plan,demoProvider);},[plan,providerTick]);

  useEffect(()=>{void compareAndSwapState({plan:planRef.current},{plan:planRef.current,activity:activityRef.current,provider:demoProvider.exportState(),writerId:writerId.current});},[]);
  useEffect(()=>subscribeState(incoming=>{
    if(incoming.writerId===writerId.current)return;
    const current=planRef.current;
    if(incoming.plan.version<current.version)return;
    const sameToken=incoming.plan.version===current.version&&incoming.plan.updatedAt===current.updatedAt;
    if(sameToken&&(!incoming.provider||incoming.provider.revision<=demoProvider.revision))return;
    demoProvider.importState(incoming.provider);planRef.current=incoming.plan;activityRef.current=incoming.activity;setPlanState(incoming.plan);setActivity(incoming.activity);setProviderTick(demoProvider.revision);setSyncMessage(`Synced authoritative version ${incoming.plan.version} from another tab.`);
  }),[]);

  const announce=useCallback((text:string,tone:'ok'|'error'='ok')=>{setToast({text,tone});window.setTimeout(()=>setToast(null),3600);},[]);
  const commit=useCallback(async(next:Plan,text:string,source:ActivitySource,detail?:string)=>{
    const expected={plan:structuredClone(planRef.current)};
    const nextActivity=[{id:uid(),text,detail:detail??sourceLabel[source],source,timestamp:new Date().toISOString(),planVersion:next.version},...activityRef.current].slice(0,40);
    const saved=await compareAndSwapState(expected,{plan:next,activity:nextActivity,provider:demoProvider.exportState(),writerId:writerId.current});
    if(!saved.ok){const authoritative=loadState();demoProvider.importState(authoritative.provider);planRef.current=authoritative.plan;activityRef.current=authoritative.activity;setPlanState(authoritative.plan);setActivity(authoritative.activity);setProviderTick(demoProvider.revision);setSyncMessage('Concurrent edit blocked; authoritative state loaded.');return saved;}
    planRef.current=next;activityRef.current=nextActivity;setPlanState(next);setActivity(nextActivity);setProviderTick(demoProvider.revision);return saved;
  },[]);
  const commitExternal=useCallback(async(next:Plan,text:string)=>{const result=await commit(next,text,'external-agent');if(result.ok)announce('Agent updated the shared workspace');return result;},[announce,commit]);

  useEffect(()=>{
    if(typeof document.modelContext?.registerTool!=='function')return;
    const controller=new AbortController();const tools=buildTools(()=>planRef.current,commitExternal,demoProvider);
    Promise.all(tools.map(tool=>document.modelContext!.registerTool(tool,{signal:controller.signal}))).then(()=>setWebmcp('active')).catch(()=>setWebmcp('error'));
    return()=>controller.abort();
  },[commitExternal]);

  const showError=(error:ToolError)=>announce(`${error.message}${error.details?.length?` ${error.details[0]}`:''}`,'error');
  const update=async(change:Record<string,unknown>,text:string):Promise<MutationOutcome>=>{
    const result=applyPlanUpdate(planRef.current,{expectedVersion:planRef.current.version,...change},demoProvider);
    if(!result.ok){showError(result.error);return result;}
    if(!result.data.changed)return {ok:true};const saved=await commit(result.data.plan,text,'human');if(!saved.ok){showError(saved.error);return saved;}return {ok:true};
  };
  const changeDate=async(date:string):Promise<MutationOutcome>=>{
    const current=planRef.current;const parsed=parseInput(constraintsSchema,{city:current.city,date,people:current.people,budget:current.budget});
    if(!parsed.ok){showError(parsed.error);return parsed;}
    if(date===current.date)return {ok:true};
    const next=createBlankPlan({date:parsed.data.date,people:current.people,budget:current.budget});next.version=current.version+1;next.preferences=current.preferences;next.changeSummary='Changed date and cleared dependent selections';
    const saved=await commit(next,'Changed date; dependent choices were cleared','human');if(!saved.ok){showError(saved.error);return saved;}return {ok:true};
  };
  const runQuickPlanner=async()=>{const current=planRef.current;const result=solvePlan({city:'Dhaka',date:current.date,people:current.people,budget:current.budget,preferences:current.preferences,dinnerDurationMinutes:current.dinnerDurationMinutes,bufferMinutes:current.bufferMinutes},current.version,undefined,demoProvider);if(!result.ok){showError(result.error);return;}const saved=await commit(result.plan,`Local preview created valid plan v${result.plan.version}`,'quick-planner','Local solver preview — not an agent call');if(!saved.ok){showError(saved.error);return;}setTab('plan');announce('Local preview found a feasible combination');};
  const quickRepair=async()=>{const result=repairPlan(planRef.current,{expectedVersion:planRef.current.version,preserveRestaurant:true,preserveMovie:false},demoProvider);if(!result.ok){showError(result.error);return;}const saved=await commit(result.plan,`Local repair restored feasibility in v${result.plan.version}`,'quick-planner','Local fallback for testing repair_plan');if(!saved.ok){showError(saved.error);return;}announce('Plan repaired while preserving dinner');};
  const approve=async()=>{const result=approvePlan(planRef.current,planRef.current.version,demoProvider);if(!result.ok){showError(result.error);return;}const saved=await commit(result.data.plan,`Human approved valid version ${result.data.plan.version}`,'human',`Bound to provider revision ${demoProvider.revision}`);if(!saved.ok){showError(saved.error);return;}announce('This exact plan and inventory revision are approved');};
  const reserve=async()=>{const result=reservePlan(planRef.current,planRef.current.version,demoProvider);if(!result.ok){if(result.plan){const saved=await commit(result.plan,`Reservation failed: ${result.error.code}`,'human',result.error.message);if(!saved.ok){showError(saved.error);return;}}showError(result.error);return;}const saved=await commit(result.data.plan,`${result.data.idempotent?'Returned':'Created'} ${result.data.reservationId}`,'human',result.data.message);if(!saved.ok){showError(saved.error);return;}announce(result.data.idempotent?'Existing confirmation returned':'Sandbox inventory confirmed');};

  return <div className="app">
    <Header tab={tab} setTab={setTab} webmcp={webmcp}/>
    <main className="main">
      <PlanStrip plan={plan} snapshot={snapshot} setTab={setTab}/>
      {tab==='goal'&&<Goal plan={plan} snapshot={snapshot} webmcp={webmcp} update={update} changeDate={changeDate} runQuickPlanner={runQuickPlanner} setTab={setTab}/>}
      {tab==='explore'&&<Explore plan={plan} snapshot={snapshot} update={update}/>}
      {tab==='plan'&&<PlanView plan={plan} snapshot={snapshot} approve={approve} reserve={reserve} quickRepair={quickRepair} setTab={setTab}/>}
      {tab==='activity'&&<ActivityView activity={activity} syncMessage={syncMessage} webmcp={webmcp}/>}
    </main>
    <div className="sr-live" aria-live="polite">{toast?.text}</div>{toast&&<div className={`toast ${toast.tone}`} role={toast.tone==='error'?'alert':'status'}>{toast.tone==='ok'?<CheckCircle2/>:<AlertTriangle/>}{toast.text}</div>}
  </div>;
}

function Header({tab,setTab,webmcp}:{tab:Tab;setTab:(tab:Tab)=>void;webmcp:WebMcpState}){
  const nav:[Tab,string,React.ReactNode][]=[['goal','1. Goal',<Sparkles/>],['explore','2. Explore',<Pencil/>],['plan','3. Plan',<ShieldCheck/>],['activity','Activity',<History/>]];
  return <header className="topbar"><Brand/><nav aria-label="Planning steps">{nav.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{icon}<span>{label}</span></button>)}</nav><WebMcpBadge state={webmcp}/></header>;
}
function Brand(){return <button className="brand" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="PlanOnIt home"><span className="brandmark">P</span><span>plan<span>on</span>it</span></button>;}
function WebMcpBadge({state}:{state:WebMcpState}){const copy={registering:'Connecting tools…',active:`Agent-ready · ${toolNames.length} tools`,unavailable:'Manual mode',error:'Tool setup failed'};return <div className={`webmcp-pill ${state}`} title={copy[state]}><span className="pulse"/>{copy[state]}</div>;}

function PlanStrip({plan,snapshot,setTab}:{plan:Plan;snapshot:ReturnType<typeof snapshotPlan>;setTab:(tab:Tab)=>void}){
  const passed=snapshot.evaluation.checks.filter(item=>item.passed).length;
  return <section className="plan-strip" aria-label="Current plan summary"><div><span className={`state-dot ${snapshot.evaluation.valid?'pass':'fail'}`}/><strong>{statusLabel(plan,snapshot.evaluation)}</strong><span>{plan.date} · {plan.people} people · {money(plan.budget)}</span></div><div className="strip-actions"><span>{passed}/{snapshot.evaluation.checks.length} checks</span><button onClick={()=>setTab('plan')}>{snapshot.evaluation.valid?'Review plan':'See what needs attention'} <ArrowRight/></button></div><details className="technical-details"><summary>Technical details</summary><span>Plan v{plan.version} · Provider revision {snapshot.evaluation.providerRevision} · State: {plan.status}</span></details></section>;
}

function Goal({plan,snapshot,webmcp,update,changeDate,runQuickPlanner,setTab}:{plan:Plan;snapshot:ReturnType<typeof snapshotPlan>;webmcp:WebMcpState;update:(change:Record<string,unknown>,text:string)=>Promise<MutationOutcome>;changeDate:(date:string)=>Promise<MutationOutcome>;runQuickPlanner:()=>void;setTab:(tab:Tab)=>void}){
  const prompt=`Plan a ${plan.date} evening in Dhaka for ${plan.people} people under ৳${plan.budget}. Use PlanOnIt's site tools, show me feasibility evidence, and leave approval to me.`;
  const copy=()=>navigator.clipboard?.writeText(prompt);
  return <>
    <section className="hero"><div className="hero-copy"><div className="eyebrow">AGENT-FIRST EVENING PLANNER</div><h1>Tell an agent what you want.<br/><span>Keep the final say.</span></h1><p>PlanOnIt gives an AI agent live planning tools, a shared draft, and hard safety gates. You inspect the evidence and approve the exact version.</p><div className="hero-actions"><button className="primary" onClick={copy}><Copy/> Copy agent request</button><button className="secondary" onClick={()=>setTab('explore')}>Build manually <ArrowRight/></button></div></div><div className="how-card"><div><span>1</span><p><strong>Set the goal</strong>Choose date, group, and budget.</p></div><div><span>2</span><p><strong>Agent builds</strong>Site tools write the same draft.</p></div><div><span>3</span><p><strong>You approve</strong>Only a valid current version proceeds.</p></div></div></section>
    <section className="goal-grid"><div className="panel constraints-panel"><div className="section-heading"><div><div className="eyebrow">YOUR GOAL</div><h2>Start with the essentials</h2></div><span>Saved automatically</span></div><ConstraintEditor key={`${plan.people}:${plan.budget}`} plan={plan} update={update} changeDate={changeDate}/></div><div className="panel agent-card"><div className="agent-icon"><Bot/></div><div className="eyebrow">USE AN AI AGENT</div><h2>{webmcp==='active'?'Your agent can use this page':'Open in a WebMCP-enabled ChatGPT browser'}</h2><p>An external agent can compare options, build or repair the shared plan, and explain its choices. Only you can approve it.</p><div className="prompt-box"><code>{prompt}</code><button aria-label="Copy agent request" onClick={copy}><Copy/></button></div><div className={`status-line ${webmcp}`}><span/>{webmcp==='active'?'Agent tools are available':'Manual planning and local preview still work'}</div></div></section>
    <section className="decision-row"><div><div className="eyebrow">YOUR NEXT STEP</div><h2>{snapshot.evaluation.valid?'Your plan is ready for review.':'Create a feasible first draft.'}</h2><p>{snapshot.evaluation.valid?'Check the itinerary, budget, and evidence before you approve.':'Use the transparent local preview, build manually, or copy the prompt for an external agent.'}</p></div><div>{snapshot.evaluation.valid?<button className="primary" onClick={()=>setTab('plan')}>Review plan <ArrowRight/></button>:<button className="primary" onClick={runQuickPlanner}><Sparkles/> Create plan preview</button>}</div></section>
  </>;
}

function ConstraintEditor({plan,update,changeDate}:{plan:Plan;update:(change:Record<string,unknown>,text:string)=>Promise<MutationOutcome>;changeDate:(date:string)=>Promise<MutationOutcome>}){
  const [people,setPeople]=useState(String(plan.people));const [budget,setBudget]=useState(String(plan.budget));const [errors,setErrors]=useState<Record<string,string>>({});
  const commitNumber=async(field:'people'|'budget',raw:string)=>{const result=await update({[field]:Number(raw)},field==='people'?'Changed party size':'Changed total budget');if(!result.ok)setErrors(current=>({...current,[field]:result.error.message}));else setErrors(current=>({...current,[field]:''}));};
  const patchPreferences=(patch:Partial<Preferences>)=>update({preferences:{...plan.preferences,...patch}},'Updated planning preferences');
  const onDate=async(value:string)=>{const result=await changeDate(value);setErrors(current=>({...current,date:result.ok?'':result.error.message}));};
  return <div className="constraint-editor">
    <label><span><MapPin/> City</span><select aria-label="City" value={plan.city} disabled><option>Dhaka</option></select></label>
    <label><span><CalendarDays/> Date</span><input aria-label="Date" type="date" min="2026-09-03" max="2026-09-16" value={plan.date} aria-invalid={Boolean(errors.date)} aria-describedby={errors.date?'date-error':undefined} onChange={event=>void onDate(event.target.value)}/>{errors.date&&<small id="date-error" className="field-error" role="alert">{errors.date}</small>}</label>
    <label><span><Utensils/> People</span><input aria-label="People" type="number" min="1" max="12" value={people} aria-invalid={Boolean(errors.people)} aria-describedby={errors.people?'people-error':undefined} onChange={event=>setPeople(event.target.value)} onBlur={()=>void commitNumber('people',people)}/>{errors.people&&<small id="people-error" className="field-error" role="alert">{errors.people}</small>}</label>
    <label><span><CircleDollarSign/> Budget</span><input aria-label="Budget" type="number" min="500" max="100000" step="100" value={budget} aria-invalid={Boolean(errors.budget)} aria-describedby={errors.budget?'budget-error':undefined} onChange={event=>setBudget(event.target.value)} onBlur={()=>void commitNumber('budget',budget)}/>{errors.budget&&<small id="budget-error" className="field-error" role="alert">{errors.budget}</small>}</label>
    <label><span><Star/> Cuisine preference</span><select aria-label="Cuisine preference" value={plan.preferences.cuisine??''} onChange={event=>patchPreferences({cuisine:event.target.value||undefined})}><option value="">Any cuisine</option>{[...new Set(restaurants.map(item=>item.cuisine))].map(item=><option key={item}>{item}</option>)}</select></label>
    <label><span><Ticket/> Movie preference</span><select aria-label="Movie preference" value={plan.preferences.movieGenre??''} onChange={event=>patchPreferences({movieGenre:event.target.value||undefined})}><option value="">Any genre</option>{[...new Set(movies.map(item=>item.genre))].map(item=><option key={item}>{item}</option>)}</select></label>
    <label><span><Navigation/> Transport</span><select aria-label="Transport preference" value={plan.preferences.transport} onChange={event=>patchPreferences({transport:event.target.value as Preferences['transport']})}><option value="lowest_cost">Lowest cost</option><option value="comfortable">Comfortable</option><option value="fastest">Fastest</option></select></label>
    <label><span><Sparkles/> Priority</span><select aria-label="Planning priority" value={plan.preferences.priority} onChange={event=>patchPreferences({priority:event.target.value as Preferences['priority']})}><option value="balanced">Balanced</option><option value="lowest_cost">Lowest cost</option><option value="highest_rated">Highest rated</option></select></label>
  </div>;
}

function Explore({plan,snapshot,update}:{plan:Plan;snapshot:ReturnType<typeof snapshotPlan>;update:(change:Record<string,unknown>,text:string)=>Promise<MutationOutcome>}){
  const currentShowtime=demoProvider.getShowtime(plan.selections.showtimeId);const currentCinema=demoProvider.getCinema(currentShowtime?.cinemaId);const currentRestaurant=demoProvider.getRestaurant(plan.selections.restaurantId);const route=demoProvider.getRoute(currentRestaurant?.locationId,currentCinema?.locationId);const shows=demoProvider.showtimesForDate(plan.date);
  return <><PageTitle eyebrow="BUILD MANUALLY" title="Choose the exact pieces." body="Every choice uses the same live availability and safety checks as the agent tools." status={snapshot.evaluation.valid?'Feasible':'Needs repair'}/>
    <section className="explore-section"><SectionTitle number="01" title="Dinner" subtitle="Only slots with enough provider capacity are shown."/><div className="card-grid">{restaurants.map(restaurant=>{const slots=demoProvider.availableRestaurantSlots(restaurant,plan.date,plan.people);return <article className={`choice-card ${plan.selections.restaurantId===restaurant.id?'selected':''}`} key={restaurant.id}><div className="choice-top"><span className="choice-emoji">{restaurant.image}</span><div><h3>{restaurant.name}</h3><p>{restaurant.cuisine} · {demoProvider.getLocation(restaurant.locationId)?.area}</p></div><span className="rating"><Star/> {restaurant.rating}</span></div><p>{restaurant.description}</p><div className="choice-meta"><span>{money(restaurant.pricePerPerson)} / person</span><span>{restaurant.openingHours}</span></div><div className="slot-row">{slots.length?slots.map(slot=><button className={plan.selections.restaurantId===restaurant.id&&plan.selections.restaurantSlot===slot.time?'active':''} key={slot.time} onClick={()=>update({restaurantId:restaurant.id,restaurantSlot:slot.time},`Selected ${restaurant.name} at ${slot.time}`)}>{prettyTime(slot.time)} <small>{slot.capacityRemaining} left</small></button>):<small className="unavailable">No capacity for this group</small>}</div></article>})}</div></section>
    <section className="explore-section"><SectionTitle number="02" title="Movie" subtitle="Movie and showtime move together as one validated choice."/><div className="card-grid">{movies.map(movie=>{const movieShows=shows.filter(item=>item.movieId===movie.id&&item.seatsRemaining>=plan.people);return <article className={`choice-card ${plan.selections.movieId===movie.id?'selected':''}`} key={movie.id}><div className="choice-top"><span className="choice-emoji">{movie.poster}</span><div><h3>{movie.title}</h3><p>{movie.genre} · {movie.durationMinutes} min</p></div><span className="rating"><Star/> {movie.rating}</span></div><p>{movie.description}</p><div className="slot-row">{movieShows.map(show=><button className={plan.selections.showtimeId===show.id?'active':''} key={show.id} onClick={()=>update({movieId:movie.id,showtimeId:show.id},`Selected ${movie.title} at ${show.startTime}`)}>{prettyTime(show.startTime)} <small>{money(show.price)} · {cinemas.find(item=>item.id===show.cinemaId)?.name.split(',')[0]}</small></button>)}</div></article>})}</div></section>
    <section className="explore-section"><SectionTitle number="03" title="Transport" subtitle="Only route-backed options appear after both venues are known."/>{route?<div className="route-card"><div className="route-summary"><RouteIcon/><div><strong>{demoProvider.getLocation(route.fromLocationId)?.name} → {demoProvider.getLocation(route.toLocationId)?.name}</strong><span>{route.distanceKm} km provider route</span></div></div><div className="transport-grid">{route.options.map(option=><button className={plan.selections.transportOptionId===option.id?'selected':''} key={option.id} onClick={()=>update({transportOptionId:option.id},`Selected ${option.name}`)}><Navigation/><strong>{option.name}</strong><span>{option.durationMinutes} min · {money(option.fare)}</span><small>{option.description}</small></button>)}</div></div>:<Empty icon={<RouteIcon/>} title="Choose dinner and a movie first" body="Then PlanOnIt can resolve a real route in its sandbox inventory."/>}</section>
  </>;
}

function PlanView({plan,snapshot,approve,reserve,quickRepair,setTab}:{plan:Plan;snapshot:ReturnType<typeof snapshotPlan>;approve:()=>void;reserve:()=>void;quickRepair:()=>void;setTab:(tab:Tab)=>void}){
  const {evaluation,restaurant,movie,showtime,cinema,transport,route}=snapshot;const failed=evaluation.checks.filter(item=>!item.passed);
  const repairPrompt=`Repair PlanOnIt plan v${plan.version}. Preserve the restaurant if possible, explain every changed dependency, and validate the result.`;
  const repaired=plan.changeSummary.toLowerCase().includes('repair')&&evaluation.valid;
  return <><PageTitle eyebrow="CURRENT PLAN" title="Your evening, ready to verify." body={`${plan.date} · ${plan.people} people · ${restaurant?.name??'Dinner'} followed by ${movie?.title??'a movie'}.`} status={statusLabel(plan,evaluation)}/>
    <details className="plan-technical"><summary>Technical audit details</summary><span>Plan v{plan.version} · Provider revision {evaluation.providerRevision} · State: {plan.status}</span></details>
    {plan.status==='reservation_failed'&&<section className="repair-callout"><div><AlertTriangle/><div><div className="eyebrow">CONFIRMATION FAILED</div><h2>Your plan is safe; no inventory was consumed.</h2><p>{plan.reservation?.failureCode}. Review the live evidence and approve again when ready.</p></div></div></section>}
    {repaired&&<section className="repair-success"><CheckCircle2/><div><div className="eyebrow">PLAN REPAIRED</div><h2>Feasibility restored without hiding the tradeoffs.</h2><ul><li>Dinner preserved where requested</li><li>Dependent movie and travel choices recalculated</li><li>Budget and schedule checks now pass</li></ul></div></section>}
    {!evaluation.valid&&<section className="repair-callout"><div><AlertTriangle/><div><div className="eyebrow">PLAN NEEDS ATTENTION</div><h2>{failed[0]?.message??'A blocking issue must be repaired.'}</h2><ul>{failed.slice(1).map(item=><li key={item.id}><strong>{item.label}:</strong> {item.message}</li>)}</ul><button className="text-button" onClick={()=>navigator.clipboard?.writeText(repairPrompt)}><Bot/> Copy agent repair prompt</button></div></div><div><button className="primary" onClick={quickRepair}><Wrench/> Repair plan now</button><button className="secondary" onClick={()=>setTab('explore')}><Pencil/> Fix manually</button></div></section>}
    <div className="plan-layout"><div className="plan-main"><section className="panel timeline"><div className="section-heading"><div><div className="eyebrow">ITINERARY</div><h2>{evaluation.timeline?'Dinner, travel, then the movie':'Complete the selections to calculate time'}</h2></div><Clock3/></div>{evaluation.timeline?<><TimelineRow icon={<Utensils/>} time={`${prettyTime(evaluation.timeline.dinnerStart)}–${prettyTime(evaluation.timeline.dinnerEnd)}`} title={restaurant?.name??'Restaurant'} detail={`${restaurant?.cuisine} · table at ${prettyTime(plan.selections.restaurantSlot)}`}/><TimelineRow icon={<Navigation/>} time={`${prettyTime(evaluation.timeline.departAt)}–${prettyTime(evaluation.timeline.arriveAt)}`} title={transport?.name??'Transport'} detail={`${route?.distanceKm} km · ${transport?.durationMinutes} min · ${plan.bufferMinutes}-min arrival buffer`}/><TimelineRow icon={<Ticket/>} time={`${prettyTime(evaluation.timeline.movieStart)}–${prettyTime(evaluation.timeline.movieEnd)}`} title={movie?.title??'Movie'} detail={`${cinema?.name} · ${showtime?.inventoryState==='committed_to_current_plan'?`${showtime.committedQuantity} seats confirmed for you`:`${showtime?.seatsRemaining} seats available now`}`}/></>:<Empty icon={<Clock3/>} title="No timeline yet" body="Restaurant, showtime, and transport are all required."/>}</section><section className="panel"><div className="section-heading"><div><div className="eyebrow">PLAN HEALTH</div><h2>{evaluation.valid?'Every blocking check passes':'Here is exactly what needs attention'}</h2></div><span className={`score-badge ${evaluation.valid?'pass':'fail'}`}>{evaluation.checks.filter(item=>item.passed).length}/{evaluation.checks.length}</span></div><CheckGrid checks={evaluation.checks}/></section></div>
    <aside className="cost-card"><div className="eyebrow">TOTAL COST</div><h2>{money(evaluation.costs.total)}</h2><div className="budget-meter"><div className={evaluation.costs.remainingBudget!==null&&evaluation.costs.remainingBudget<0?'over':''} style={{width:`${evaluation.costs.total===null?0:Math.min(100,(evaluation.costs.total/plan.budget)*100)}%`}}/></div><div className="budget-row"><span>of {money(plan.budget)}</span><strong className={evaluation.costs.remainingBudget!==null&&evaluation.costs.remainingBudget<0?'danger':''}>{evaluation.costs.remainingBudget===null?'Incomplete':evaluation.costs.remainingBudget>=0?`${money(evaluation.costs.remainingBudget)} left`:`${money(Math.abs(evaluation.costs.remainingBudget))} over`}</strong></div><div className="breakdown"><CostRow label="Dinner" value={evaluation.costs.restaurant} detail={`${plan.people} × ${money(restaurant?.pricePerPerson)}`}/><CostRow label="Movie" value={evaluation.costs.movie} detail={`${plan.people} × ${money(showtime?.price)}`}/><CostRow label="Transport" value={evaluation.costs.transport} detail="route-specific fare"/></div><div className={`approval-note ${evaluation.valid?'pass':'fail'}`}>{evaluation.valid?<CheckCircle2/>:<ShieldCheck/>}<span>{evaluation.valid?'Ready for your explicit approval.':'Approval and reservation are blocked.'}</span></div>{plan.status==='reserved'?<div className="reservation-confirmed"><CheckCircle2/><strong>{plan.reservation?.id}</strong><span>Sandbox provider inventory committed</span></div>:plan.status==='approved'?<button className="primary full" onClick={reserve}><ShieldCheck/> Confirm sandbox reservation</button>:<button className="primary full" disabled={!evaluation.valid} onClick={approve}><ShieldCheck/> Approve this plan</button>}<button className="text-button full" onClick={()=>setTab('explore')}><Pencil/> Edit choices</button><small className="fine-print">A reservation commits controlled sandbox inventory. No real provider or payment is contacted.</small></aside></div>
  </>;
}

function ActivityView({activity,syncMessage,webmcp}:{activity:Activity[];syncMessage:string;webmcp:WebMcpState}){return <><PageTitle eyebrow="AUDIT TRAIL & AGENT GUIDE" title="One workspace, visible changes." body="Human and WebMCP edits share versions, validation, storage, and provider inventory." status={webmcp==='active'?'Agent connected':'Manual mode'}/><div className="activity-layout"><section className="panel"><div className="section-heading"><div><div className="eyebrow">VERSION HISTORY</div><h2>Recent workspace activity</h2></div><span className="live-dot">● {syncMessage}</span></div>{activity.length?<div className="activity-list">{activity.map(item=><div className="activity-row" key={item.id}><span className={`activity-avatar ${item.source}`}>{item.source==='external-agent'?<Bot/>:item.source==='quick-planner'?<RefreshCw/>:item.source==='system'?<History/>:'YOU'}</span><div><strong>{item.text}</strong><span>{item.detail} · v{item.planVersion} · {new Date(item.timestamp).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</span></div></div>)}</div>:<Empty icon={<History/>} title="No edits yet" body="Agent and human changes will appear here."/>}</section><aside className="panel guide"><div className="eyebrow">AGENT GUIDE</div><h2>12 tools, four jobs</h2><dl><div><dt>Discover</dt><dd>restaurants, details, availability, showtimes, transport</dd></div><div><dt>Plan</dt><dd>create, inspect, validate, calculate cost</dd></div><div><dt>Collaborate</dt><dd>versioned update and signature repair</dd></div><div><dt>Confirm</dt><dd>provider-backed sandbox reservation after human approval</dd></div></dl><p>All tool inputs are strict objects. Side effects are disclosed in descriptions, stale versions fail, and approval cannot be supplied by a tool.</p></aside></div></>}

function PageTitle({eyebrow,title,body,status}:{eyebrow:string;title:string;body:string;status:string}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{body}</p></div><span className="status-chip"><Check/> {status}</span></div>}
function SectionTitle({number,title,subtitle}:{number:string;title:string;subtitle:string}){return <div className="section-title"><span>{number}</span><div><h2>{title}</h2><p>{subtitle}</p></div></div>}
function Empty({icon,title,body}:{icon:React.ReactNode;title:string;body:string}){return <div className="empty-state">{icon}<h3>{title}</h3><p>{body}</p></div>}
function TimelineRow({icon,time,title,detail}:{icon:React.ReactNode;time:string;title:string;detail:string}){return <div className="timeline-row"><span className="timeline-icon">{icon}</span><time>{time}</time><div><strong>{title}</strong><span>{detail}</span></div></div>}
function CheckGrid({checks}:{checks:ReturnType<typeof evaluatePlan>['checks']}){return <div className="check-grid">{checks.map(item=><div className={item.passed?'pass':'fail'} key={item.id}>{item.passed?<CheckCircle2/>:<XCircle/>}<div><strong>{item.label}</strong><span>{item.message}</span></div></div>)}</div>}
function CostRow({label,value,detail}:{label:string;value:number|null;detail:string}){return <div><span>{label}<small>{detail}</small></span><strong>{money(value)}</strong></div>}
