import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Bot, Check, ChevronRight, CircleHelp, Clock3, MapPin, Pencil, Plane, Plus, RefreshCw, ShieldCheck, Sparkles, Star, Ticket, Utensils, WalletCards, X } from 'lucide-react';
import './styles.css';
import { buildTools, toolNames } from './tools';
import { getMovie, getRestaurant, getRide, getShowtime, makeAgentPlan, planSnapshot, totalCost } from './domain';
import { initialPlan, movies, restaurants, rides } from './data';
import { Activity, Plan, Tab } from './types';

const money=(n:number)=>`৳${n.toLocaleString('en-IN')}`;
const now=()=>new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
function App(){
 const [tab,setTab]=useState<Tab>('overview'); const [plan,setPlanState]=useState<Plan>(initialPlan); const planRef=useRef(plan); const [activity,setActivity]=useState<Activity[]>([]); const [showAgent,setShowAgent]=useState(false); const [toast,setToast]=useState('');
 const snapshot=useMemo(()=>planSnapshot(plan),[plan]);
 const addActivity=(text:string,type:'agent'|'human'|'system'='human',detail='')=>setActivity(a=>[{id:crypto.randomUUID(),text,detail,type,time:now()},...a].slice(0,8));
 const setPlan=(p:Plan, text:string)=>{planRef.current=p;setPlanState(p);addActivity(text,'agent','WebMCP tool execution');setToast('Plan updated by your agent');setTimeout(()=>setToast(''),2800);};
 const updatePlanState=(updater: (p:Plan)=>Plan)=>{setPlanState(p=>{const next=updater(p);planRef.current=next;return next;});};
 useEffect(()=>{const tools=buildTools(()=>planRef.current,setPlan); if(document.modelContext){tools.forEach(t=>document.modelContext!.registerTool(t).catch(()=>{}));} },[]);
 const select=(key: keyof Plan,value:string)=>{updatePlanState(p=>({...p,[key]:value,approved:false}));addActivity(`You changed ${key.replace('Id','')}`,'human','Manual edit');};
 const approve=()=>{updatePlanState(p=>({...p,approved:true}));addActivity('You approved the draft','human','Ready for simulated reservation');setToast('Draft approved — ready to reserve');setTimeout(()=>setToast(''),2800);};
 return <div className="app"><header className="topbar"><div className="brand"><div className="brandmark">P</div><span>plan<span>on</span>it</span></div><div className="header-right"><div className="webmcp-pill"><span className="pulse"/>WebMCP active <span className="tool-count">{toolNames.length} tools</span></div><button className="avatar">TM</button></div></header>
 <main className="shell"><aside className="sidebar"><div className="eyebrow">YOUR EVENING</div><nav><Nav active={tab==='overview'} icon={<Sparkles/>} text="Overview" onClick={()=>setTab('overview')}/><Nav active={tab==='explore'} icon={<Plane/>} text="Explore" onClick={()=>setTab('explore')}/><Nav active={tab==='plan'} icon={<Ticket/>} text="My plan" onClick={()=>setTab('plan')} badge={plan.restaurantId? '1':''}/></nav><div className="sidebar-card"><div className="mini-icon"><Bot size={17}/></div><div><strong>Agent-ready</strong><p>Ask your agent to build or tune this plan.</p></div><ChevronRight size={16}/></div><div className="sidebar-bottom"><ShieldCheck size={16}/><span>Your approval is always required</span></div></aside>
 <section className="content">{tab==='overview'&&<Overview plan={plan} snapshot={snapshot} onExplore={()=>setTab('explore')} onBuild={()=>setShowAgent(true)} activity={activity}/>} {tab==='explore'&&<Explore plan={plan} select={select}/>} {tab==='plan'&&<PlanView plan={plan} snapshot={snapshot} select={select} approve={approve} onExplore={()=>setTab('explore')} activity={activity}/>}</section></main>{showAgent&&<AgentModal onClose={()=>setShowAgent(false)} onBuild={p=>{setPlan(p,'Agent assembled your evening');setShowAgent(false);setTab('plan')}}/>}{toast&&<div className="toast"><Check size={18}/>{toast}</div>}</div>
}
function Nav({active,icon,text,onClick,badge}:{active:boolean;icon:React.ReactNode;text:string;onClick:()=>void;badge?:string}){return <button className={`nav-item ${active?'active':''}`} onClick={onClick}>{icon}<span>{text}</span>{badge&&<i>{badge}</i>}</button>}
function Overview({plan,snapshot,onExplore,onBuild,activity}:{plan:Plan;snapshot:any;onExplore:()=>void;onBuild:()=>void;activity:Activity[]}){return <><div className="welcome"><div><div className="eyebrow">FRIDAY · {plan.date}</div><h1>Make an evening of it<span className="dot">.</span></h1><p>One thoughtful plan, assembled around what matters to you.</p></div><button className="primary" onClick={onBuild}><Bot size={18}/> Ask your agent <ArrowRight size={17}/></button></div><div className="goal-card"><div className="goal-copy"><div className="goal-kicker"><Sparkles size={15}/> YOUR CURRENT BRIEF</div><h2>Dinner + a movie in Dhaka</h2><p>For {plan.people} people · under {money(plan.budget)} · {plan.preferences}</p><button className="text-button" onClick={onBuild}>Edit brief <Pencil size={14}/></button></div><div className="goal-stat"><span>Budget</span><strong>{money(plan.budget)}</strong><small>{snapshot.total?`${money(snapshot.total)} planned`:'Nothing selected yet'}</small></div></div><div className="section-head"><div><div className="eyebrow">YOUR PLAN</div><h2>{plan.restaurantId?'A promising start':'Start shaping your evening'}</h2></div><button className="ghost" onClick={onExplore}>Explore options <ArrowRight size={16}/></button></div>{plan.restaurantId?<PlanStrip snapshot={snapshot}/>:<div className="empty-plan"><div className="empty-orb"><Plus/></div><h3>Your plan is waiting for a few good ideas.</h3><p>Browse the options or let your agent find a balanced combination.</p><button className="secondary" onClick={onExplore}>Explore services <ArrowRight size={16}/></button></div>}<ActivityFeed activity={activity}/></>}
function PlanStrip({snapshot}:{snapshot:any}){return <div className="plan-strip"><CardIcon icon={<Utensils/>} label="Dinner" value={snapshot.restaurant||'Choose a restaurant'} meta={snapshot.restaurant?'Selected':'Not selected'} tone="coral"/><div className="connector"/><CardIcon icon={<Ticket/>} label="Movie" value={snapshot.movie||'Choose a movie'} meta={snapshot.showtime||'Not selected'} tone="blue"/><div className="connector"/><CardIcon icon={<Plane/>} label="Getting there" value={snapshot.ride||'Choose transport'} meta={snapshot.ride?'Estimated':'Not selected'} tone="green"/><div className="strip-total"><span>EST. TOTAL</span><strong>{money(snapshot.total)}</strong><small className={snapshot.remainingBudget<0?'danger':''}>{snapshot.remainingBudget>=0?`${money(snapshot.remainingBudget)} left`:`${money(Math.abs(snapshot.remainingBudget))} over budget`}</small></div></div>}
function CardIcon({icon,label,value,meta,tone}:{icon:React.ReactNode;label:string;value:string;meta:string;tone:string}){return <div className="service-card"><div className={`service-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function Explore({plan,select}:{plan:Plan;select:(key:keyof Plan,value:string)=>void}){return <><div className="page-title"><div><div className="eyebrow">DISCOVER</div><h1>Find your ingredients<span className="dot">.</span></h1><p>Pick a few favourites. We’ll keep the whole evening in view.</p></div><div className="location"><MapPin size={16}/> Dhaka <ChevronRight size={15}/></div></div><div className="explore-grid"><div className="explore-section"><div className="section-head compact"><div><h2><span className="number">01</span> Dinner</h2><p>Highly-rated spots for a good beginning.</p></div><span className="count">{restaurants.length} options</span></div><div className="option-list">{restaurants.map(r=><Option key={r.id} icon={r.image} title={r.name} subtitle={`${r.cuisine} · ${r.area}`} price={`${money(r.pricePerPerson)} / person`} rating={r.rating} selected={plan.restaurantId===r.id} onClick={()=>select('restaurantId',r.id)}/>)}</div></div><div className="explore-section"><div className="section-head compact"><div><h2><span className="number">02</span> Something to watch</h2><p>Tonight’s best available screens.</p></div><span className="count">{movies.length} options</span></div><div className="option-list">{movies.map(m=><Option key={m.id} icon={m.poster} title={m.title} subtitle={`${m.genre} · ${m.duration} min`} price={`${money(m.showtimes[0].price)} / ticket`} rating={m.rating/2} selected={plan.movieId===m.id} onClick={()=>{select('movieId',m.id);select('showtimeId',m.showtimes[0].id)}}/>)}</div></div><div className="explore-section full"><div className="section-head compact"><div><h2><span className="number">03</span> Get there</h2><p>Simple estimates between your evening’s stops.</p></div></div><div className="ride-grid">{rides.map(r=><Option key={r.id} icon={r.id==='metro-ride'?'🚇':'🚗'} title={r.name} subtitle={`${r.eta} · ${r.comfort}`} price={money(r.fare)} selected={plan.rideId===r.id} onClick={()=>select('rideId',r.id)}/>)}</div></div></div></>}
function Option({icon,title,subtitle,price,rating,selected,onClick}:{icon:string;title:string;subtitle:string;price:string;rating?:number;selected:boolean;onClick:()=>void}){return <button className={`option ${selected?'selected':''}`} onClick={onClick}><div className="option-emoji">{icon}</div><div className="option-main"><strong>{title}</strong><span>{subtitle}</span>{rating&&<small><Star size={12} fill="currentColor"/> {rating.toFixed(1)}</small>}</div><div className="option-price"><strong>{price}</strong>{selected?<span className="chosen"><Check size={13}/> Added</span>:<span>Add to plan <Plus size={13}/></span>}</div></button>}
function PlanView({plan,snapshot,select,approve,onExplore,activity}:{plan:Plan;snapshot:any;select:(key:keyof Plan,value:string)=>void;approve:()=>void;onExplore:()=>void;activity:Activity[]}){const r=getRestaurant(plan.restaurantId),m=getMovie(plan.movieId),s=getShowtime(plan.movieId,plan.showtimeId),ride=getRide(plan.rideId);return <><div className="page-title"><div><div className="eyebrow">DRAFT PLAN · {plan.approved?'APPROVED':'NEEDS YOUR REVIEW'}</div><h1>Your Dhaka evening<span className="dot">.</span></h1><p>Friday, September 4 · {plan.people} people · {plan.preferences}</p></div><button className="ghost" onClick={onExplore}>+ Add or change <Pencil size={15}/></button></div><div className="plan-layout"><div><div className="timeline"><TimelineItem icon={<Utensils/>} tone="coral" time="6:00 PM" title={r?.name||'Choose a restaurant'} detail={r?`${r.cuisine} · ${r.area} · ${money(r.pricePerPerson)} / person`:'Dinner is still open'} onChange={onExplore}/><TimelineItem icon={<Plane/>} tone="green" time="7:45 PM" title={ride?.name||'Choose transport'} detail={ride?`${ride.eta} · ${money(ride.fare)} estimated fare`:'A ride between stops'} onChange={onExplore}/><TimelineItem icon={<Ticket/>} tone="blue" time={s?.time||'8:30 PM'} title={m?.title||'Choose a movie'} detail={m?`${m.cinema} · ${m.genre} · ${money(s?.price||0)} / ticket`:'A showtime that fits'} onChange={onExplore}/></div><ActivityFeed activity={activity}/></div><aside className="cost-card"><div className="eyebrow">COST SNAPSHOT</div><h2>{money(snapshot.total)}</h2><div className="budget-meter"><div style={{width:`${Math.min(100,(snapshot.total/plan.budget)*100)}%`}}/></div><div className="budget-row"><span>of {money(plan.budget)} budget</span><strong className={snapshot.remainingBudget<0?'danger':''}>{snapshot.remainingBudget>=0?`${money(snapshot.remainingBudget)} left`:`${money(Math.abs(snapshot.remainingBudget))} over`}</strong></div><div className="breakdown"><div><span>🍛 Dinner <small>{plan.people} × {money(r?.pricePerPerson||0)}</small></span><strong>{money((r?.pricePerPerson||0)*plan.people)}</strong></div><div><span>🎬 Movie <small>{plan.people} × {money(s?.price||0)}</small></span><strong>{money((s?.price||0)*plan.people)}</strong></div><div><span>🚗 Transport <small>estimated</small></span><strong>{money(ride?.fare||0)}</strong></div></div><div className="approval"><ShieldCheck size={17}/><span>Nothing is booked without your approval.</span></div><button className={`primary full-btn ${plan.approved?'approved':''}`} onClick={approve}>{plan.approved?<><Check size={18}/> Draft approved</>:<>Review & approve <ArrowRight size={17}/></>}</button></aside></div></>}
function TimelineItem({icon,tone,time,title,detail,onChange}:{icon:React.ReactNode;tone:string;time:string;title:string;detail:string;onChange:()=>void}){return <div className="timeline-item"><div className={`timeline-icon ${tone}`}>{icon}</div><div className="timeline-time">{time}</div><div className="timeline-info"><strong>{title}</strong><span>{detail}</span></div><button className="icon-btn" aria-label="Change selection" onClick={onChange}><Pencil size={15}/></button></div>}
function ActivityFeed({activity}:{activity:Activity[]}){return <div className="activity"><div className="section-head compact"><div><div className="eyebrow">ACTIVITY</div><h2>Shared workspace</h2></div><span className="live-dot">● live</span></div>{activity.length===0?<p className="muted">Your plan history will appear here as you and your agent make decisions together.</p>:activity.map(a=><div className="activity-row" key={a.id}><div className={`activity-avatar ${a.type}`}>{a.type==='agent'?<Bot size={14}/>:a.type==='human'?'TM':<Check size={14}/>}</div><div><strong>{a.text}</strong><span>{a.detail} · {a.time}</span></div></div>)}</div>}
function AgentModal({onClose,onBuild}:{onClose:()=>void;onBuild:(p:Plan)=>void}){const [people,setPeople]=useState(3),[budget,setBudget]=useState(5000),[pref,setPref]=useState('highly-rated dinner, a movie afterward');return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={onClose}><X/></button><div className="modal-icon"><Bot/></div><div className="eyebrow">WEBMCP AGENT BRIEF</div><h2>Give your agent the shape of the evening.</h2><p>PlanOnIt will search, compare, and assemble a draft across services. You stay in charge of every final decision.</p><label>How many people?<div className="stepper"><button onClick={()=>setPeople(Math.max(1,people-1))}>−</button><strong>{people}</strong><button onClick={()=>setPeople(Math.min(12,people+1))}>+</button></div></label><label>Total budget<input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>What are you in the mood for?<input value={pref} onChange={e=>setPref(e.target.value)}/></label><button className="primary full-btn" onClick={()=>onBuild(makeAgentPlan({...initialPlan,people,budget,preferences:pref}))}><Sparkles size={17}/> Assemble my draft <ArrowRight size={17}/></button><small className="modal-foot"><ShieldCheck size={14}/> The agent can prepare plans, never make purchases.</small></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
