import { applyPlanUpdate, evaluatePlan, hasActiveReservation, repairPlan, reservePlan, snapshotPlan, solvePlan, startNewPlan } from './domain';
import { demoProvider, InventoryProvider } from './providers';
import { Plan, ToolError, ToolResult } from './types';
import { availabilitySchema, createPlanSchema, emptyInputSchema, fail, parseInput, repairPlanSchema, reservePlanSchema, restaurantDetailsSchema, searchRestaurantsSchema, showtimesSchema, startNewPlanSchema, transportSchema } from './validation';

export interface WebTool {name:string;title:string;description:string;inputSchema:Record<string,unknown>;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>Promise<unknown>;}
export const toolNames=['search_restaurants','get_restaurant_details','check_restaurant_availability','find_showtimes','estimate_transport','create_evening_plan','get_current_plan','validate_plan','update_plan','repair_plan','calculate_total_cost','reserve_plan','start_new_plan'] as const;
const objectSchema=(properties:Record<string,unknown>,required:string[]=[],extra:Record<string,unknown>={}):Record<string,unknown>=>({type:'object',properties,required,additionalProperties:false,...extra});
const id={type:'string',minLength:1};
const shortText={type:'string',minLength:2,maxLength:40};
const supportedDates=Array.from({length:14},(_,index)=>`2026-09-${String(index+3).padStart(2,'0')}`);
const date={type:'string',format:'date',enum:supportedDates,description:'Supported demo inventory window: 2026-09-03 through 2026-09-16.'};
const budget={type:'integer',minimum:500,maximum:100000};
const preferencesJson={type:'object',description:'Structured ranking preferences that materially affect candidate scoring.',properties:{cuisine:shortText,movieGenre:shortText,minRestaurantRating:{type:'number',minimum:1,maximum:5},transport:{type:'string',enum:['lowest_cost','comfortable','fastest'],default:'lowest_cost'},priority:{type:'string',enum:['balanced','lowest_cost','highest_rated'],default:'balanced'},timing:{type:'string',enum:['relaxed','compact'],default:'relaxed'}},additionalProperties:false};
const version={type:'integer',minimum:1,description:'Current positive plan version from get_current_plan. Mutations reject stale versions.'};
type CommitResult=void|ToolResult<unknown>;

export function buildTools(getPlan:()=>Plan,commit:(plan:Plan,activity:string)=>CommitResult|Promise<CommitResult>,provider:InventoryProvider=demoProvider):WebTool[]{
  const context=()=>({planVersion:getPlan().version,providerRevision:provider.revision});
  const success=<T extends object>(data:T)=>({ok:true,data:{...data,context:context()}});
  const contextualError=(result:{ok:false;error:ToolError})=>({ok:false,error:{...result.error,context:context()}});
  const committed=async(plan:Plan,activity:string)=>{const result=await commit(plan,activity);return result&&result.ok===false?contextualError(result):null;};
const tools:WebTool[]=[
  {name:'search_restaurants',title:'Search available restaurants',description:'Find demo restaurants that match city, date, party size, cuisine, rating, price, and current remaining table capacity. Use before selecting dinner. Returns IDs and available slots; never books.',inputSchema:objectSchema({city:{type:'string',enum:['Dhaka']},date,people:{type:'integer',minimum:1,maximum:12},cuisine:shortText,minRating:{type:'number',minimum:1,maximum:5},maxPricePerPerson:{type:'integer',minimum:100,maximum:10000}},['city','date','people']),annotations:{readOnlyHint:true},execute:async(input)=>{
    const parsed=parseInput(searchRestaurantsSchema,input);if(!parsed.ok)return parsed;
    const results=provider.searchRestaurants(parsed.data).map(item=>({id:item.id,name:item.name,cuisine:item.cuisine,rating:item.rating,pricePerPerson:item.pricePerPerson,location:provider.getLocation(item.locationId),openingHours:item.openingHours,availableSlots:provider.availableRestaurantSlots(item,parsed.data.date,parsed.data.people)}));
    return success({results,count:results.length,guidance:results.length?'Use restaurantId and one returned slot together in update_plan.':'No matching capacity. Relax a filter or choose another supported date.'});
  }},
  {name:'get_restaurant_details',title:'Get restaurant details',description:'Read one restaurant’s location, pricing, hours, party limits, and current provider-style availability inventory by ID.',inputSchema:objectSchema({restaurantId:id},['restaurantId']),annotations:{readOnlyHint:true},execute:async(input)=>{
    const parsed=parseInput(restaurantDetailsSchema,input);if(!parsed.ok)return parsed;const restaurant=provider.getRestaurant(parsed.data.restaurantId);if(!restaurant)return {ok:false,error:{code:'UNKNOWN_RESTAURANT',message:'Restaurant ID was not found.',field:'restaurantId',retryable:true}};
    return success({...restaurant,slots:provider.restaurantSlots(restaurant,getPlan().date,getPlan()),location:provider.getLocation(restaurant.locationId)});
  }},
  {name:'check_restaurant_availability',title:'Check table availability',description:'Check current remaining table capacity for a known restaurant, supported date, and party size. Use immediately before plan creation or replacement.',inputSchema:objectSchema({restaurantId:id,date,people:{type:'integer',minimum:1,maximum:12}},['restaurantId','date','people']),annotations:{readOnlyHint:true},execute:async(input)=>{
    const parsed=parseInput(availabilitySchema,input);if(!parsed.ok)return parsed;const restaurant=provider.getRestaurant(parsed.data.restaurantId);if(!restaurant)return {ok:false,error:{code:'UNKNOWN_RESTAURANT',message:'Restaurant ID was not found.',field:'restaurantId',retryable:true}};
    const slots=provider.availableRestaurantSlots(restaurant,parsed.data.date,parsed.data.people);return success({restaurantId:restaurant.id,date:parsed.data.date,people:parsed.data.people,available:slots.length>0,slots});
  }},
  {name:'find_showtimes',title:'Find compatible showtimes',description:'Find movie showtimes in the plan city on an exact supported date with enough current seats. Returns atomic movieId/showtimeId pairs, cinema location, duration, and price.',inputSchema:objectSchema({city:{type:'string',enum:['Dhaka']},date,people:{type:'integer',minimum:1,maximum:12},genre:shortText},['city','date','people']),annotations:{readOnlyHint:true},execute:async(input)=>{
    const parsed=parseInput(showtimesSchema,input);if(!parsed.ok)return parsed;const results=provider.searchShowtimes(parsed.data).map(item=>{const movie=provider.getMovie(item.movieId);const cinema=provider.getCinema(item.cinemaId);return {movieId:item.movieId,showtimeId:item.id,title:movie?.title,genre:movie?.genre,rating:movie?.rating,durationMinutes:movie?.durationMinutes,cinema,startTime:item.startTime,pricePerTicket:item.price,seatsRemaining:item.seatsRemaining};});
    return success({results,count:results.length,guidance:results.length?'Always update movieId and showtimeId together.':'No showtime has enough seats on this date.'});
  }},
  {name:'estimate_transport',title:'Estimate venue transport',description:'Return route-specific distance, duration, and fare options between known PlanOnIt location IDs. Unknown or unsupported routes return ROUTE_NOT_FOUND; no fares are invented.',inputSchema:objectSchema({fromLocationId:id,toLocationId:id},['fromLocationId','toLocationId']),annotations:{readOnlyHint:true},execute:async(input)=>{
    const parsed=parseInput(transportSchema,input);if(!parsed.ok)return parsed;const from=provider.getLocation(parsed.data.fromLocationId);const to=provider.getLocation(parsed.data.toLocationId);if(!from||!to)return {ok:false,error:{code:'UNKNOWN_LOCATION',message:'Both endpoints must be known PlanOnIt location IDs.',field:!from?'fromLocationId':'toLocationId',retryable:true}};const route=provider.getRoute(from.id,to.id);if(!route)return {ok:false,error:{code:'ROUTE_NOT_FOUND',message:`No supported demo route connects ${from.name} to ${to.name}.`,retryable:true}};
    return success({routeId:route.id,from,to,distanceKm:route.distanceKm,options:route.options});
  }},
  {name:'create_evening_plan',title:'Create a feasible evening',description:'Evaluate restaurant slots × showtimes × venue routes × transport options, reject invalid combinations, rank valid ones using structured preferences, and atomically replace the shared draft. It never approves or reserves.',inputSchema:objectSchema({city:{type:'string',enum:['Dhaka']},date,people:{type:'integer',minimum:1,maximum:12},budget,preferences:preferencesJson,dinnerDurationMinutes:{type:'integer',minimum:45,maximum:150,default:75},bufferMinutes:{type:'integer',minimum:5,maximum:45,default:15}},['city','date','people','budget','preferences']),annotations:{readOnlyHint:false},execute:async(input)=>{
    const parsed=parseInput(createPlanSchema,input);if(!parsed.ok)return parsed;const currentPlan=getPlan();if(hasActiveReservation(currentPlan))return contextualError(fail('WORKSPACE_HAS_ACTIVE_RESERVATION',`Plan version ${currentPlan.version} holds confirmed reservation ${currentPlan.reservation!.id}. The reserved plan is immutable and cannot be replaced, because its table and seat inventory is still committed. Call start_new_plan to begin a new plan while that reservation stays visible and committed.`,undefined,false,[`Active reservation ${currentPlan.reservation!.id} for version ${currentPlan.reservation!.version}.`,'Use start_new_plan to start a fresh plan without hiding or cancelling it.']) as {ok:false;error:ToolError});const result=solvePlan(parsed.data,currentPlan.version,undefined,provider);if(!result.ok)return result;const conflict=await committed(result.plan,`External agent created valid plan v${result.plan.version}`);if(conflict)return conflict;return success({plan:snapshotPlan(result.plan,provider),considered:result.considered,explanation:result.explanation,nextStep:'Ask the human to inspect feasibility evidence; WebMCP cannot approve for them.'});
  }},
  {name:'get_current_plan',title:'Inspect shared plan',description:'Read the current persisted shared draft, version, selections, current provider entities, timeline, cost breakdown, approval state, and full feasibility evidence.',inputSchema:objectSchema({}),annotations:{readOnlyHint:true},execute:async(input)=>{const parsed=parseInput(emptyInputSchema,input);if(!parsed.ok)return parsed;const current=getPlan();const ledger=provider.listReservations();return success({...snapshotPlan(current,provider),activeReservation:hasActiveReservation(current)?current.reservation:undefined,reservationLedger:ledger.map(item=>({...item,belongsToCurrentPlan:item.planId===current.id&&item.version===current.version,supersededByNewerPlan:item.version<current.version}))});}},
  {name:'validate_plan',title:'Validate shared plan',description:'Recompute every blocking constraint against the current mutable provider revision: completeness, ownership, city, capacity, showtime integrity, route, chronology, and budget. Does not mutate.',inputSchema:objectSchema({}),annotations:{readOnlyHint:true},execute:async(input)=>{const parsed=parseInput(emptyInputSchema,input);return parsed.ok?success({version:getPlan().version,...evaluatePlan(getPlan(),provider)}):parsed;}},
  {name:'update_plan',title:'Atomically update plan',description:'Apply a version-checked atomic change. Restaurant requires restaurantId+restaurantSlot; movie requires movieId+showtimeId. Invalid IDs, mismatches, wrong dates, routes, empty changes, and stale versions are rejected. Identical input is a no-op and does not increment the version.',inputSchema:objectSchema({expectedVersion:version,restaurantId:id,restaurantSlot:{type:'string',pattern:'^([01]\\d|2[0-3]):[0-5]\\d$'},movieId:id,showtimeId:id,transportOptionId:id,budget,people:{type:'integer',minimum:1,maximum:12},preferences:preferencesJson},['expectedVersion'],{minProperties:2,dependentRequired:{restaurantId:['restaurantSlot'],restaurantSlot:['restaurantId'],movieId:['showtimeId'],showtimeId:['movieId']}}),annotations:{readOnlyHint:false},execute:async(input)=>{
    const result=applyPlanUpdate(getPlan(),input,provider);if(!result.ok)return result;if(result.data.changed){const conflict=await committed(result.data.plan,`External agent updated plan to v${result.data.plan.version}`);if(conflict)return conflict;}return success({...result.data,plan:snapshotPlan(result.data.plan,provider)});
  }},
  {name:'repair_plan',title:'Repair invalid shared plan',description:'Signature collaboration tool: inspect the current invalid human-edited draft, preserve the requested restaurant and/or movie, search dependent alternatives, and atomically replace it with the highest-ranked feasible version. Requires the current version.',inputSchema:objectSchema({expectedVersion:version,preserveRestaurant:{type:'boolean',default:true},preserveMovie:{type:'boolean',default:false}},['expectedVersion']),annotations:{readOnlyHint:false},execute:async(input)=>{
    const parsed=parseInput(repairPlanSchema,input);if(!parsed.ok)return parsed;const result=repairPlan(getPlan(),parsed.data,provider);if(!result.ok)return result;const conflict=await committed(result.plan,`External agent repaired constraints in v${result.plan.version}`);if(conflict)return conflict;return success({plan:snapshotPlan(result.plan,provider),considered:result.considered,explanation:result.explanation,tradeoff:'Dependent choices were changed only where required to restore every blocking constraint.'});
  }},
  {name:'calculate_total_cost',title:'Calculate reliable total',description:'Return per-person-scaled dinner and ticket costs plus route-specific transport fare. Invalid or incomplete references return null components and failed feasibility evidence, never a misleading zero-cost success.',inputSchema:objectSchema({}),annotations:{readOnlyHint:true},execute:async(input)=>{const parsed=parseInput(emptyInputSchema,input);if(!parsed.ok)return parsed;const evaluation=evaluatePlan(getPlan(),provider);return success({version:getPlan().version,costs:evaluation.costs,budgetCheck:evaluation.checks.find(item=>item.id==='budget')});}},
  {name:'reserve_plan',title:'Confirm sandbox reservation',description:'Consequential sandbox action. Commits mutable in-app table and seat inventory only for the exact current version and provider revision after human approval. Stale, invalid, unapproved, conflicted, and failed attempts consume nothing; retries are idempotent. No real provider or payment is contacted.',inputSchema:objectSchema({expectedVersion:version,confirmation:{type:'string',enum:['CONFIRM_SIMULATED_RESERVATION'],description:'Backward-compatible exact acknowledgement that this is a controlled sandbox reservation.'}},['expectedVersion','confirmation']),annotations:{readOnlyHint:false},execute:async(input)=>{
    const parsed=parseInput(reservePlanSchema,input);if(!parsed.ok)return parsed;const result=await reservePlan(getPlan(),parsed.data.expectedVersion,provider,async pending=>{await commit(pending,`External agent reservation pending for v${pending.version}`);});if(!result.ok){if(result.plan){const conflict=await committed(result.plan,`External agent reservation failed: ${result.error.code}`);if(conflict)return conflict;}return contextualError(result);}const conflict=await committed(result.data.plan,`External agent confirmed sandbox reservation ${result.data.reservationId}`);if(conflict)return conflict;return success(result.data);
  }},
  {name:'start_new_plan',title:'Start a new plan lifecycle',description:'Explicitly begin a new plan after a reservation was confirmed. The previous reservation is never cancelled, detached, or hidden: its committed inventory stays with its own plan version and remains readable through get_current_plan\u2019s reservationLedger. Required before create_evening_plan can run on a workspace that holds an active reservation.',inputSchema:objectSchema({expectedVersion:version,acknowledgeExistingReservation:{type:'boolean',default:true,description:'Acknowledges that any active reservation stays committed and visible in the ledger.'}},['expectedVersion']),annotations:{readOnlyHint:false},execute:async(input)=>{
    const parsed=parseInput(startNewPlanSchema,input);if(!parsed.ok)return parsed;const result=startNewPlan(getPlan(),parsed.data.expectedVersion,provider);if(!result.ok)return result;
    const conflict=await committed(result.data.plan,result.data.archivedReservation?`External agent started a new plan; ${result.data.archivedReservation.id} stays committed`:`External agent started a new plan v${result.data.plan.version}`);if(conflict)return conflict;
    return success({plan:snapshotPlan(result.data.plan,provider),archivedReservation:result.data.archivedReservation,reservationLedger:result.data.reservationLedger,guidance:result.data.archivedReservation?`Reservation ${result.data.archivedReservation.id} remains committed to version ${result.data.archivedReservation.version} and is still listed in reservationLedger.`:'No active reservation existed; a fresh draft was started.'});
  }}
 ];
 return tools.map(tool=>({...tool,execute:async(input)=>{const result=await tool.execute(input);if(!result||typeof result!=='object')return result;const record=result as {ok?:boolean;error?:Record<string,unknown>;data?:Record<string,unknown>};if(record.ok===false&&record.error&&!record.error.context)return {...record,error:{...record.error,context:context()}};if(record.ok===true&&record.data&&!record.data.context)return {...record,data:{...record.data,context:context()}};return result;}}));
}

export function resultErrorCode(result:unknown):string|undefined{if(!result||typeof result!=='object')return;const record=result as Partial<ToolResult<unknown>>;return record.ok===false&&record.error?record.error.code:undefined;}
