import { getMovie, getRestaurant, getRide, getShowtime, makeAgentPlan, planSnapshot, totalCost } from './domain';
import { movies, restaurants, rides } from './data';
import { Plan } from './types';
export const toolNames=['search_restaurants','find_showtimes','estimate_ride','create_evening_plan','get_current_plan','update_plan','calculate_total_cost','reserve_plan'];
const obj=(properties:Record<string,unknown>,required:string[]=[])=>( {type:'object',properties,required,additionalProperties:false} );
export function buildTools(getPlan:()=>Plan,setPlan:(p:Plan, activity:string)=>void){
 return [
 {name:'search_restaurants',title:'Search restaurants',description:'Find dinner options by city, cuisine, rating, and per-person price. Use this before choosing a restaurant for an evening plan.',inputSchema:obj({city:{type:'string',description:'City, e.g. Dhaka'},cuisine:{type:'string',description:'Optional cuisine preference'},maxPricePerPerson:{type:'number',description:'Maximum price in Bangladeshi taka per person'},minRating:{type:'number',description:'Minimum rating from 1 to 5'}},['city']),annotations:{readOnlyHint:true},execute:async(input:any)=>{const result=restaurants.filter(r=>r.city.toLowerCase()===input.city.toLowerCase() && (!input.cuisine||r.cuisine.toLowerCase().includes(input.cuisine.toLowerCase())) && (!input.maxPricePerPerson||r.pricePerPerson<=input.maxPricePerPerson) && (!input.minRating||r.rating>=input.minRating)).map(r=>({id:r.id,name:r.name,cuisine:r.cuisine,area:r.area,rating:r.rating,pricePerPerson:r.pricePerPerson})); return {ok:true,results:result};}},
 {name:'find_showtimes',title:'Find movie showtimes',description:'Find movies and available showtimes for a date. Include enough seats for the requested group.',inputSchema:obj({date:{type:'string',format:'date',description:'Show date in YYYY-MM-DD'},people:{type:'number',minimum:1,maximum:12,description:'Number of seats needed'},genre:{type:'string',description:'Optional genre preference'}},['date','people']),annotations:{readOnlyHint:true},execute:async(input:any)=>({ok:true,results:movies.filter(m=>(!input.genre||m.genre.toLowerCase().includes(input.genre.toLowerCase()))).flatMap(m=>m.showtimes.filter(s=>s.date===input.date&&s.seats>=input.people).map(s=>({movieId:m.id,title:m.title,genre:m.genre,rating:m.rating,cinema:m.cinema,showtimeId:s.id,time:s.time,price:s.price,seatsAvailable:s.seats})))} )},
 {name:'estimate_ride',title:'Estimate a ride',description:'Compare deterministic demo transport options between two neighbourhoods. Returns fare and travel time.',inputSchema:obj({from:{type:'string',description:'Pickup neighbourhood'},to:{type:'string',description:'Destination neighbourhood'}},['from','to']),annotations:{readOnlyHint:true},execute:async(input:any)=>({ok:true,results:rides.map(r=>({...r,from:input.from,to:input.to}))})},
 {name:'create_evening_plan',title:'Assemble an evening plan',description:'Create a coherent dinner, movie, and transport plan from a high-level goal. This changes the current draft only; it never books anything.',inputSchema:obj({city:{type:'string',description:'City'},date:{type:'string',format:'date',description:'Date in YYYY-MM-DD'},people:{type:'number',minimum:1,maximum:12,description:'Party size'},budget:{type:'number',minimum:500,description:'Total budget in Bangladeshi taka'},preferences:{type:'string',description:'Cuisine, genre, or experience preferences'}},['city','date','people','budget']),annotations:{readOnlyHint:false},execute:async(input:any)=>{const p=makeAgentPlan(input);setPlan(p,'Agent assembled a complete draft from your constraints');return {ok:true,plan:planSnapshot(p),message:'Draft created. Human approval is required before reservation.'};}},
 {name:'get_current_plan',title:'Inspect current plan',description:'Read the current shared draft, selections, timeline, total cost, and budget status.',inputSchema:obj({}),annotations:{readOnlyHint:true},execute:async()=>({ok:true,plan:planSnapshot(getPlan())})},
 {name:'update_plan',title:'Update a plan selection',description:'Change one or more selections on the shared draft. Use IDs returned by search tools. This does not reserve anything.',inputSchema:obj({restaurantId:{type:'string'},movieId:{type:'string'},showtimeId:{type:'string'},rideId:{type:'string'}},[]),annotations:{readOnlyHint:false},execute:async(input:any)=>{const current=getPlan(); if(input.restaurantId&&!getRestaurant(input.restaurantId))return {ok:false,error:'Unknown restaurant ID'}; if(input.movieId&&!getMovie(input.movieId))return {ok:false,error:'Unknown movie ID'}; if(input.rideId&&!getRide(input.rideId))return {ok:false,error:'Unknown ride ID'}; const p={...current,...input,approved:false};setPlan(p,'Agent updated the shared draft');return {ok:true,plan:planSnapshot(p)};}},
 {name:'calculate_total_cost',title:'Calculate total cost',description:'Calculate dinner, movie tickets, transport fare, total, and remaining budget for the current draft.',inputSchema:obj({}),annotations:{readOnlyHint:true},execute:async()=>({ok:true,...planSnapshot(getPlan())})},
 {name:'reserve_plan',title:'Prepare reservation draft',description:'Prepare a simulated reservation summary only after the human has approved the current plan in the UI. Never claim a real booking.',inputSchema:obj({confirmation:{type:'string',description:'Must be exactly APPROVE_DRAFT'}},['confirmation']),annotations:{readOnlyHint:false},execute:async(input:any)=>{if(input.confirmation!=='APPROVE_DRAFT')return {ok:false,error:'Human confirmation required. Approve the draft in the UI first.'};if(!getPlan().approved)return {ok:false,error:'Human must approve this exact draft in the UI before reservation.'};return {ok:true,status:'simulated_reservation_ready',message:'Demo reservation prepared. No real external transaction was made.',plan:planSnapshot(getPlan())};}},
 ];
}
